### ISSUE TITLE
Filtrado de eventos por tag

### ISSUE THREAD

**Issue by nelopuchades** [achamorro-dev/eventoswiki#1]
* **Estoy reportando...**
  - [ ] un bug
  - [x] una solicitud de funcionalidad

* **¿Quieres solicitar una funcionalidad o reportar un bug?**

Solicitar una funcionalidad

* **¿Cuál es el comportamiento actual?**

Actualmente no podemos filtrar por tag cuando cada evento si que tiene varios

* **¿Cuál es el comportamiento esperado?**

El comportamiento esperado es poder tener algún sistema de badges arriba del grid de eventos que permita filtrar fácilmente por tipo de evento

* **¿Cuál es la motivación/caso de uso para cambiar el comportamiento?**

Permitir a los usuarios buscar más fácilmente los tipos de eventos en los que están interesados

* **Información extra**

En mi cabeza me estoy imaginando [este tipo de badges](https://flowbite.com/docs/components/badge/) arriba del grid que al hacer click, filtre automáticamente los eventos

**Comment by nelodev** [comment]
🫶🏻 Voy a comenzar a trabajar yo mismo en la funcionalidad, se acepta cualquier tipo de sugerencia

**Comment by nelodev** [comment]
Tengo una dudilla para debatir con vosotrxs (especialmente con @achamorro-dev). Trabajando en esta funcionalidad me he encontrado con un problema: El pintar las tags actuales en las cards de los events del color del event, hace que los colores no estén asociados a las tags si no al evento.

¿Cuál es el problema de este approach? Muy sencillo. Al montar el sistema de tags arriba, nos podemos encontrar en una situación en la que queramos filtrar por 'Open Space' pero... ¿de qué color es el tag de Open Space al que hacemos click para filtrar? ¿Rojo? Y si hacemos click y se filtra correctamente por eventos con tag 'Open Space' pero los tags de Open Space son de diferentes colores en las cards... queda un poco raruno.

Así que ahora mismo hay que tomar una decisión de dos posibles:

### Decisión 1 (la más sencilla)

Sistema de tags arriba pero consistente en palabras que al hacer click, se ponen en negrita para indicar que se ha "activado" ese filtro. Pierden personalidad los tags pero te permite mantener la asociación tag-evento.

### Decisión 2 (la menos sencilla pero mejor en mi opinión)

Cambiar los colores de las tags a nivel de tag y no a nivel de evento. Tendremos que aceptar que las tags no "pegarán" con el fondo del evento, pero a la hora de filtrar será mucho más cómodo visualmente.

**Propuesta muy simple**

Entre todos los eventos tenemos ahora mismo 11 tags. Mi propuesta de colores para cada tag es la siguiente (he intentado seguir un poco los colores asociados a cada concepto (amarillo para python, azul para php... etc).

- General
    - Azul oscuro con tono morado
    - [#3B3561](https://www.colorhexa.com/3b3561)

- Devs
    - Rojo
    - [#FF0D21](https://www.colorhexa.com/ff0d21)

- UI/UX
    - Rosa fuerte
    - [#ED217C](https://www.colorhexa.com/ed217c)

- Agile
    - Azul oscuro
    - [#1B065E](https://www.colorhexa.com/1b065e)

- Api
    - Naranja clarito
    - [#FE9920](https://www.colorhexa.com/fe9920)

- Open space
    - Azul medio (ni oscuro ni claro)
    - [#3066BE](https://www.colorhexa.com/3066be)

- Design
    - Azul mar chillón
    - [#00FFC5](https://www.colorhexa.com/00ffc5)

- AI
    - Morado
    - [#8C2155](https://www.colorhexa.com/8c2155)

- Talleres
    - Marrón
    - [#6B4B3E](https://www.colorhexa.com/6b4b3e)

- Php
    - Azul con toque morado
    - [#7A86B8](https://www.colorhexa.com/7a86b8)

- Python
    - Amarillo con toque dorado
    - [#FFD343](https://www.colorhexa.com/ffd343)

¿Qué pensáis?

**Comment by achamorro-dev** [comment]
¡Muchas gracias @nelodev! La idea de dar colores a los tags inicialmente estaba pensada para que cada evento tuviera su toque de personalización.

Dicho esto, ambas opciones me parecen correctas:

* Opción 1: podríamos utilizar los colores de la temática de la web.
* Opción 2: lo bueno es que podrías diferenciar temática por color aunque podemos caer en la fiesta del color.

Creo que inicialmente me quedaría con la primera opción. Puede que abramos otro hilo para discutir acerca de las tags y las posibles categorías de las tags, por ejemplo:

* Por tipo: meetup, charla, conferencia
* Online o presencial
* Categoría: devs, diseño, cloud
* etc

Por lo que puede que la "discusión" sobre dotar de colores a cada etiqueta se podría tener en ese otro hilo. ¿Qué te parece?

**Comment by nelodev** [comment]
Perfecto, se puede implementar una primera iteración con la opción 1 y más tarde discutir en otro hilo como dices un mejorado sistema de tags con nuevos colores y hacer una segunda iteración para implementarlo.

Eso si, tengo una dudilla. ¿A qué te refieres cuando dices en la opción 1 que "podríamos utilizar los colores de la temática de la web? Si en teoría van a ser opciones en negro y al seleccionarlas se van a poner en negrita, ¿no?

¡Gracias!

**Comment by achamorro-dev** [comment]
Perdona el lío 😅 Cuando digo de utilizar los colores de la temática de la web me refiero a los colores `primary` y `accent` configurados en el fichero de configuración de tailwind.

**Comment by nelodev** [comment]
¡Hola! Estoy con el desarrollo y tengo una dudilla. ¿Cómo te gustaría el dinamismo de los tags? ¿Que siempre estén los tags de todos los eventos aunque hayas filtrado? ¿O que sea un filtrado sucesivo y se vayan eliminando los tags cuyos eventos ya no aparezcan?

La primera es lógicamente mucho más sencilla de implementar, por lo que es mi preferida y a partir de ahí ya podemos ir iterando.

¿Qué opinas?

**Comment by achamorro-dev** [comment]
Me parece bien la primera opción.

No estoy seguro de si es buena experiencia para el usuario que desaparezcan cosas dependiendo de lo que selecciones.

Me gusta más la idea de filtros inclusivos 😇
