### ISSUE TITLE
Añadir nuevo evento Penpot Fest 2024

### ISSUE THREAD

**Issue by leonardogb** [achamorro-dev/eventoswiki#102]
- **Nombre o título del evento**:
Penpot Fest 2024
- **Descripción corta**:
Penpot Fest es el evento de Diseño que reúne a diseñadores y desarrolladores en Barcelona.
- **Fecha de inicio**:
5 de junio de 2024
- **Fecha de fin**:
7 de junio de 2024
- **Localización del evento**:
Teatro Lliure, 1 Plaça de Margarida Xirgu 08004 Barcelona España [Ver mapa](https://maps.app.goo.gl/Y2RTAfcDeQRsTgpd6)
- **Imagen de portada**:
![Penpot fest](https://penpotfest.org/wp-content/uploads/2024/02/Captura-de-Pantalla-2024-02-15-a-las-15.25.40.png)
- **Web del evento**:
https://penpotfest.org/
- **Redes sociales**:
  - Linkedin: https://www.linkedin.com/company/penpot/
  - Twitter: https://twitter.com/penpotapp
  - Github: https://github.com/penpot
  - Youtube: https://www.youtube.com/c/Penpot
  - Instagram: https://instagram.com/penpot.app
- **Detalles**(esta información aparecerá como contenido del evento):

¡El evento de diseño Penpot Fest se acerca! Barcelona, 5-7 de junio.

Puedes esperar un programa diverso sobre Diseño, Código y Open Source, una fiesta de bienvenida, talleres prácticos y mucho tiempo para hacer networking.

También habrá tiempo para otras actividades divertidas y deliciosa gastronomía local en la soleada (¡con suerte!) y acogedora Barcelona.

¡Ven a aprender, compartir conocimientos y conectar con otras mentes creativas y potenciales colaboradores de todo el mundo!

El lugar principal elegido para esta edición es el Teatre Lliure en Montjuïc, Barcelona, ampliamente reconocido como un centro líder de creación y puesta en escena en España.

Penpot Fest es organizado por Penpot, la herramienta de diseño de código abierto para colaboración en diseño y código.

[Penpot Fest 2023](https://www.youtube.com/playlist?list=PLgcCPfOv5v56-fghJo2dHNBqL9zlDTslh)

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/penpot-fest

¡Muchas gracias!
