### ISSUE TITLE
Añadir nuevo evento: Global Azure

### ISSUE THREAD

**Issue by svg153** [achamorro-dev/eventoswiki#105]
### Nombre o título del evento

Global Azure

### Web del evento

https://globalazure.es/

### Descripción corta

Global Azure 2024 is here!
Over 3 days, communities around the world are organizing localized hybrid events and live streams for everyone around the world to join and learn about Azure from the best-in-class community leaders.

https://blog.globalazure.net/Blog/Post/323/Welcome-to-Global-Azure-2024

### Fecha de inicio

18/04/2024

### Fecha de fin

20/04/2024

### Localización del evento

Online, Madrid, Barcelona y Zaragoza

### Detalles

Este evento tiene una, una característica especial, es un evento que se da globalmente y las comunidades organizan charlas en distintos lugares. Empezando el 18 de abril. El viernes 19 de abril habrá charlas presenciales en Barcelona y el sábado 20 habrá en Madrid y Zaragoza https://globalazure.es/

**Comment by achamorro-dev** [comment]
✅ ¡Añadidos! Puedes verlos por aquí:

https://www.eventos.wiki/eventos/2024/global-azure-barcelona
https://www.eventos.wiki/eventos/2024/global-azure-madrid
https://www.eventos.wiki/eventos/2024/global-azure-zaragoza

¡Muchas gracias!
