### ISSUE TITLE
Añadir nuevo evento: 

### ISSUE THREAD

**Issue by fredpalas** [achamorro-dev/eventoswiki#107]
### Nombre o título del evento

State of PHP on 2024 Barcelona PHP meet up

### Web del evento

https://meetu.ps/e/N5msq/tBmG2/i

### Descripción corta

What's is the state of PHP on 2024?

Adrián Pastén from Collective minds will explain how they modern and clean architectures promote an organize project, terms as Domain Driver Design, Event Architecture and how the newest functionality of PHP8.3 help they to improve code quality, testability, and decoupling the code from the infrastructure.
Agenda

18:30 - Welcome and introduction of Collective Minds Radiology
18:45 - 1st Talk State of PHP 2024
19:30 - 2nd Talk
20:00 - Networking, drinks and pizzas

### Fecha de inicio

07/05/2024

### Fecha de fin

07/05/2024

### Localización del evento

Barcelona Health Hub

### Detalles

Location:
Barcelona Health Hub
Recinto Modernista de Sant Pau
C/ de St. Antoni Maria Claret, 167, Horta-Guinardó, 08025 Barcelona

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/barcelona-php-state-of-php-2024

¡Muchas gracias!
