### ISSUE TITLE
Añadir nuevo evento: DevOps Days Cáceres

### ISSUE THREAD

**Issue by carlos-lopez-vecino** [achamorro-dev/eventoswiki#113]
### Nombre o título del evento

DevOps Days Cáceres

### Web del evento

https://devopsdays.cc

### Descripción corta

DevopsDays Cáceres es un evento sin ánimo de lucro, que intenta rellenar la ausencia de conferencias tecnológicas enfocadas al mundo open source que existe en esta región de España.

### Fecha de inicio

03/04/2024

### Fecha de fin

04/04/2024

### Localización del evento

Complejo Cultural San Francisco, Cáceres

### Redes sociales

https://www.instagram.com/devopsdayscc/, https://www.linkedin.com/company/devopsdayscc/, https://twitter.com/DevOpsDaysCC

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/devopsdays-cc

¡Muchas gracias!
