### ISSUE TITLE
LambdaWorld Cadiz 2024

### ISSUE THREAD

**Issue by asiermarques** [achamorro-dev/eventoswiki#115]
### Nombre o título del evento

LambdaWorld

### Web del evento

https://www.lambda.world

### Descripción corta

The largest Functional programming event in South Europe.

### Fecha de inicio

02-10-2024

### Fecha de fin

04-10-2024

### Localización del evento

Cadiz, Spain

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/lambda-world

¡Muchas gracias!
