### ISSUE TITLE
Bilbostack 2025

### ISSUE THREAD

**Issue by asiermarques** [achamorro-dev/eventoswiki#116]
### Nombre o título del evento

Bilbostack

### Web del evento

https://bilbostack.com

### Descripción corta

13ª Edición de la cita tecnológica anual más esperada en Bilbao

### Fecha de inicio

25-01-2025

### Fecha de fin

25-01-2025

### Localización del evento

Bilbao, España

### Imagen de portada

https://2024.bilbostack.com/bg.jpg

### Redes sociales

https://twitter.com/bilbostack

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2025/bilbostack

¡Muchas gracias!
