### ISSUE TITLE
Añadir nuevo evento: 

### ISSUE THREAD

**Issue by anabuigues** [achamorro-dev/eventoswiki#137]
### Nombre o título del evento

Introducción a Event Modeling

### Web del evento

https://www.meetup.com/es-ES/collaborative-modeling-madrid/events/301422063/

### Descripción corta

Creada por [Adam Dymitruk](https://www.linkedin.com/in/eventmodeling/) es un método que se enfoca en capturar y describir el flujo de eventos en un sistema. A través de este enfoque, los equipos pueden entender cómo las entidades del sistema interactúan a lo largo del tiempo, proporcionando una visión clara y completa del comportamiento del sistema.

Ayuda a tener una visión clara del comportamiento del sistema a través del tiempo facilitando la colaboración entre desarrolladores, expertos de negocio y otras partes interesadas. Además nos sirve como una documentación actualizada del sistema que es fácil de entender y mantener.

EM se utiliza en Adaptech group para ayudar a sus clientes en proyectos de transformación para automatizar partes del negocio, eliminar riesgos y ejecutar rápidamente un servicio.

En esta ocasión dedicaremos una sesión para introducirnos a EM. Nos sentimos honrados de poder contar con [Alexandra Moxin](https://www.linkedin.com/in/alexandra933/), Chief Strategy Officer de Adaptech group, que nos introducirá a su uso y a ejemplos de aplicación en proyectos.

### Fecha de inicio

11/06/2024 18:30

### Fecha de fin

11/06/2024 20:00

### Localización del evento

Online

### Imagen de portada

https://secure.meetupstatic.com/photos/event/d/8/0/a/600_521515306.webp?w=750

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/como-introduccion-a-event-modeling

¡Muchas gracias!
