### ISSUE TITLE
Product Hackers Conference

### ISSUE THREAD

**Issue by edugonzlz** [achamorro-dev/eventoswiki#138]
### Nombre o título del evento

Product Hackers Conference

### Web del evento

https://conference.producthackers.com

### Descripción corta

The Growth Conference

### Fecha de inicio

25 Junio

### Fecha de fin

27 Junio

### Localización del evento

Madrid

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/product-hackers-conference

¡Muchas gracias!
