### ISSUE TITLE
Wey Wey Web

### ISSUE THREAD

**Issue by lsybarguen** [achamorro-dev/eventoswiki#14]
**Wey Wey Web**: 
_A Yay-Yay conf for UI lovers_
 **15th December**
**16th December**
**Málaga**
![banner_eventoswiki](https://user-images.githubusercontent.com/12547113/193256698-ffd93976-d12a-4dcb-ba2f-ec504e639b66.png)
**https://www.weyweyweb.com**:
**https://twitter.com/jotb23**:
**https://www.linkedin.com/company/j-on-the-beach/**:
**https://www.youtube.com/c/Jonthebeach**:
**Wey Wey Web**
Wey Wey Web is a tech conference about User Interfaces.

From software development to creative design, including UX and product design. A 2 days of fun to mingle with interface lovers.

**Technical Talks**
Wey Wey Web is all about different technologies, best practices, and methodologies related to Web development. No matter if you are into Javascript, PHP, Python, WASM, Java or C#. If you are dealing with the User Interface, then THIS IS YOUR PLACE!

**Topics**
- Web programming
- JS frameworks
- Web design UX/UI
- Product design
- Mobile development

This is the first edition of the event and it will take place in Malaga on the 15th and 16th of December.

It is organised by the same team as [J On The Beach](https://www.jonthebeach.com/).

**Comment by achamorro-dev** [comment]
✅ Done!

https://eventos.wiki/eventos/2022/wey-wey-web
