### ISSUE TITLE
Meetup: A tale of implementing the Storj Rust bindings

### ISSUE THREAD

**Issue by ifraixedes** [achamorro-dev/eventoswiki#141]
### Nombre o título del evento

A tale of implementing the Storj Rust bindings

### Web del evento

https://www.meetup.com/rust-girona/events/301594780/

### Descripción corta

A journey from the ground up to create Rust bindings for Storj Libuplink with their design decisions, peculiarities, and troubles along the way.

### Fecha de inicio

26/06/2024

### Fecha de fin

26/06/2024

### Localización del evento

Girona, Spain

### Imagen de portada

https://secure.meetupstatic.com/photos/event/d/0/6/5/600_521693349.webp?w=750

### Redes sociales

https://x.com/FundacioNord https://www.instagram.com/fundacionord_/  https://www.linkedin.com/company/fundacionord/

### Detalles

A journey from the ground up to create Rust bindings for Storj Libuplink with their design decisions, peculiarities, and troubles along the way.

📅 dimecres 26 de juny a les 06:30h

📍 Centre Cívic Barri Vell-Mercadal (Sala 3)

🤝 Networking: Al final de la presentació, tindrem una sessió de networking on podràs conèixer altres assistents, compartir idees i establir connexions.

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/rust-girona-tale-implementing-stork-rust-bindings

¡Muchas gracias!
