### ISSUE TITLE
Proactividad: cómo adelantarte a las necesidades de tus clientes/usuarios con Salesforce

### ISSUE THREAD

**Issue by DevoteamSpain** [achamorro-dev/eventoswiki#143]
### Nombre o título del evento

Proactividad: cómo adelantarte a las necesidades de tus clientes/usuarios con Salesforce

### Web del evento

https://acloud.devo.team/znCYl

### Descripción corta

Te presentamos la Interacción Personalizada Inteligente, una solución innovadora que utiliza asistentes virtuales personalizados para ofrecer respuestas precisas y adaptadas a cada cliente.

Gracias a la integración de Amazon con Salesforce a través de MuleSoft, los asistentes no solo responden consultas, sino que también aprenden y mejoran con cada interacción, llevando la atención al cliente a un nuevo nivel de eficiencia y satisfacción.

¿Te imaginas poder agrupar las consultas que tengan una temática común y poder dar respuesta de la manera más eficiente y personalizada, usando la IA Gen? ¡Ya es posible!

Únete al próximo evento que se organiza en las oficinas de AWS el próximo día 3 de julio a las 9:30 AM.

**¿Qué te espera en el evento?**
**Aprende de los Expertos:** Conoce de primera mano como líderes del sector implementan estas tecnologías avanzadas.

**Demostraciones en Vivo:** Observa en acción cómo los asistentes virtuales personalizados pueden transformar la experiencia del cliente.

**Networking:** Conéctate con otros profesionales y comparte experiencias y estrategias sobre la mejora del servicio al cliente.

**Casos de Éxito:** Descubre historias reales de empresas que ya están beneficiándose de esta tecnología.

**Agenda del Evento:**
9:30 AM – Café de Bienvenida
10:00 AM – Introducción a la IA de Amazon y Salesforce
11:00 AM – Demostración en Vivo – Devoteam
11:45 AM – Casos de Éxito
12:15 PM – Café y Networking

Devoteam participa en este evento, demostrando cómo nuestras soluciones innovadoras están transformando el servicio al cliente.

**¡No pierdas esta oportunidad única de revolucionar el servicio al cliente con las tecnologías más avanzadas! ¡Te esperamos!**

### Fecha de inicio

3/07/2024

### Fecha de fin

3/07/2024

### Localización del evento

Oficinas AWS Madrid - Torre Foster, Castellana 259A, Madrid

### Imagen de portada

https://es.devoteam.com/wp-content/uploads/sites/23/2024/05/Banner-EVENTO-web-2.png

**Comment by DevoteamSpain** [comment]
El evento es en las **Oficinas AWS Madrid - Torre Foster, Castellana 259A, Madrid**
**Link del evento:** [](https://acloud.devo.team/znCYl)

**Comment by achamorro-dev** [comment]
Hola @DevoteamSpain ,

¿Este evento sigue adelante? Acabo de darlo de alta pero me he fijado en la web del evento y en el registro pone que ha sido cancelado.

<img width="1429" alt="image" src="https://github.com/achamorro-dev/eventoswiki/assets/1499378/1ca90375-e9ff-42db-b1d9-8e1309608df6">

**Comment by DevoteamSpain** [comment]
Hola Alberto,
nos lo cancelaron ayer. Qué rapidez.
Lo elimino.
Muchas gracias.


Nekane ARRIBAS GARCÍA
Digital Marketing Manager
Devoteam Spain
+34 626 16 74 32 <+34+626+16+74+32>
+34 91 376 88 20 <+34+91+376+88+20>
***@***.***
www.devoteam.com <https://es.devoteam.com/>
[image: Infinite Data Driven]
[image: Devoteam at Linkedin] <https://www.linkedin.com/company/devoteam>
[image: Devoteam at Youtube]
<https://www.youtube.com/watch?v=Lrk4lQJ82bI&t=3s>
[image: Devoteam at Twitter] <https://twitter.com/devoteames>

**Comment by achamorro-dev** [comment]
Siento esa cancelación...

Yo lo elimino, no os preocupéis.
