### ISSUE TITLE
#CodeMeet Madrid:Redefiniendo la Seguridad: El impacto de la IA en la Ciberseguridad

### ISSUE THREAD

**Issue by Nattalcual** [achamorro-dev/eventoswiki#144]
### Nombre o título del evento

#CodeMeet Madrid:Redefiniendo la Seguridad: El impacto de la IA en la Ciberseguridad

### Web del evento

https://community.codemotion.com/codemotion-espana/meetups/codemeet-madrid-redefiniendo-la-seguridad-el-impacto-de-la-ia-en-la-ciberseguridad

### Descripción corta

Organizado por Codemotion y Veracode, el 17 de septiembre a las 18:00h descubre cómo la inteligencia artificial está transformando la ciberseguridad con una ponencia de Veracode y una mesa redonda sobre desafíos y soluciones en IA y seguridad. Aprende, conecta e inspírate.

### Fecha de inicio

17/09/2024

### Fecha de fin

17/09/2024

### Localización del evento

ILAB

### Imagen de portada

https://drive.google.com/file/d/1bbp_ZSvRVIokej34EbmzBDc7MMDus9po/view?usp=sharing

### Redes sociales

https://www.linkedin.com/company/codemotion/

### Detalles

Organizado por Codemotion y Veracode, el 17 de septiembre a las 18:00h descubre cómo la inteligencia artificial está transformando la ciberseguridad con una ponencia de Veracode y una mesa redonda sobre desafíos y soluciones en IA y seguridad. Aprende, conecta e inspírate.

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/codemotion-codemeet-madrid-redefiniendo-la-seguridad-el-impacto-de-la-ia-en-la-ciberseguridad

¡Muchas gracias!
