### ISSUE TITLE
Añadir nuevo evento: #CodeMeet Madrid: Nuestra Historia: Celebrando los logros profesionales y lecciones aprendidas

### ISSUE THREAD

**Issue by Nattalcual** [achamorro-dev/eventoswiki#145]
### Nombre o título del evento

#CodeMeet Madrid: Nuestra Historia: Celebrando los logros profesionales y lecciones aprendidas

### Web del evento

#CodeMeet Madrid: Nuestra Historia: Celebrando los logros profesionales y lecciones aprendidas

### Descripción corta

En este meetup, te invitamos a ser parte de un panel dinámico que explorará las historias de éxito y los aprendizajes clave de mujeres líderes en tecnología. Nuestro panel estará compuesto por profesionales destacadas que compartirán sus experiencias personales, desafíos y cómo han logrado impulsar la innovación en sus campos.

### Fecha de inicio

10/10/2024

### Fecha de fin

10/10/2024

### Localización del evento

Attico - Maria de Molina

### Imagen de portada

https://drive.google.com/file/d/18TIHTIxdOGH1FcJW4siaX3rsbeRr5d4N/view?usp=sharing

**Comment by Nattalcual** [comment]
Esta es cuadrada: https://drive.google.com/file/d/18TIHTIxdOGH1FcJW4siaX3rsbeRr5d4N/view?usp=sharing
Esta grafica es horizontal: https://drive.google.com/file/d/18TIHTIxdOGH1FcJW4siaX3rsbeRr5d4N/view?usp=sharing
Redes sociales: https://www.linkedin.com/company/codemotion/

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/codemotion-codemeet-nuestra-historia-celebrando-los-logros-profesionales-y-lecciones-aprendidas

¡Muchas gracias!
