### ISSUE TITLE
Añadir nuevo evento: MiduConf

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#146]
### Nombre o título del evento

MiduConf

### Web del evento

https://www.miduconf.com/

### Descripción corta

Conoce el futuro de la programación

### Fecha de inicio

12/09/2024

### Fecha de fin

12/09/2024

### Localización del evento

https://www.twitch.tv/midudev

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/miduconf

¡Muchas gracias!
