### ISSUE TITLE
Añadir nuevo evento: Postgres Ibiza

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#147]
### Nombre o título del evento

PGIBZ 2024

### Web del evento

https://pgibz.io

### Descripción corta

International conference
English-only! We expect attendees from all around the world.

Community Event
Organized by the non-for-profit [Fundación PostgreSQL](https://postgresql.fund/).

Ibiza
The island where everything is possible.

Networking, networking
Unique, relaxed, cozy environment for networking. Take the hallway track to the beach!

Sponsors
Central, big location for products and services information, demos. Show off!

BYOF
Bring Your Own Family. Come earlier, stay for longer. Best time of the year in one of the best Summer locations in the world.

### Fecha de inicio

09/09/2024

### Fecha de fin

11/09/2024

### Localización del evento

Palacio de congresos de Ibiza

### Redes sociales

https://twitter.com/pg_ibz https://instagram.com/pg_ibz

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/pgibz

¡Muchas gracias!
