### ISSUE TITLE
Añadir nuevo evento: Rooted CON

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#148]
### Nombre o título del evento

RootedCON

### Web del evento

https://www.rootedcon.com/

### Descripción corta

Congreso
La conferencia de seguridad informática Rooted CON nació con el propósito de promover el intercambio de conocimientos entre los miembros de la comunidad de seguridad.

RootedLabs
Conjunto de actividades formativas de un día de duración que se realizan durante los tres días previos a RootedCON.

Bootcamps
Cursos avanzados de más de un día de duración con especialidad concreta en una temática.

### Fecha de inicio

15/10/2024

### Fecha de fin

16/10/2024

### Localización del evento

Kinépolis Madrid Ciudad de la Imagen C/Edgar Neville s/n, Ciudad de la Imagen, Madrid

### Redes sociales

https://twitter.com/pg_ibz https://instagram.com/pg_ibz

**Comment by alcastrob** [comment]
Las redes sociales están mal. Son:
- https://twitter.com/rootedcon
- https://www.facebook.com/groups/rootedcon/
- https://www.linkedin.com/groups?gid=1969438

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/rooted-con-valencia

¡Muchas gracias!
