### ISSUE TITLE
Añadir nuevo evento: XConf Europe 2024

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#149]
### Nombre o título del evento

XConf Europe 2024

### Web del evento

https://www.thoughtworks.com/about-us/events/xconf/2024/europe

### Descripción corta

For more than a decade XConf by Thoughtworks has been our flagship event for technologists by technologists who care deeply about software and its impact on the world. We want to create a day where like-minded professionals can talk about their passion and experience in a relaxed and casual atmosphere. Thus year we are headin to Barcelona! Register for XConf Europe 2024 in Barcelona on September 19 and get ready for an exciting one-day, two-track tech event for technologists, by technologists.

### Fecha de inicio

19/09/2024

### Fecha de fin

19/09/2024

### Localización del evento

Fàbrica Moritz Barcelona  41 Ronda de Sant Antoni 08011 Barcelona

### Redes sociales

https://www.linkedin.com/company/thoughtworks https://www.facebook.com/Thoughtworks https://www.twitter.com/thoughtworks https://www.youtube.com/user/thoughtworks https://www.instagram.com/thoughtworks/

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/xconf-europe

¡Muchas gracias!
