### ISSUE TITLE
Añadir nuevo evento: Xops Cpmference 2024

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#150]
### Nombre o título del evento

Xops Conference

### Web del evento

https://xopsconference.com/

### Descripción corta

Xops Conference 2024 es el evento imprescindible para profesionales de XOps, operaciones de TI y tecnología. Acompáñanos para aprender de expertos de la industria, descubrir las últimas tendencias y expandir tu red profesional. No te pierdas la oportunidad de ser parte de una comunidad que está moldeando el futuro del desarrollo y las operaciones tecnológicas.

Más de 1000 participantes en Madrid.
Más de 10,000 participantes online despues de la conferencia
Más de 20 speakers de diferentes países.

### Fecha de inicio

22/11/2024

### Fecha de fin

23/11/2024

### Localización del evento

Escuela Técnica Superior de Ingeniería de Sistemas Informáticos. Universidad Politécnica de Madrid.  Campus Sur de la UPM, C. de Alan Turing, s/n, 28031 Madrid

### Redes sociales

https://twitter.com/XopsConference

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/xops-conference

¡Muchas gracias!
