### ISSUE TITLE
Añadir nuevo evento: JSConf España

### ISSUE THREAD

**Issue by GermanDG6** [achamorro-dev/eventoswiki#152]
### Nombre o título del evento

JSConf España

### Web del evento

web: https://jsconfes.com/

### Descripción corta

Conferencia internacional de JavaScript en España

### Fecha de inicio

2025-03-01T08:00:00.000Z

### Fecha de fin

2025-03-01T08:00:00.000Z

### Localización del evento

La Nave, Madrid

### Detalles

1ª Edición de la conferencia internacional de JavaScript

¡Aprende del mejor talento de la comunidad hispana!

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2025/jsconf-espana

¡Muchas gracias!
