### ISSUE TITLE
Añadir nuevo evento: Festa Open Source Girona 2024

### ISSUE THREAD

**Issue by ctrl-alt-d** [achamorro-dev/eventoswiki#153]
### Nombre o título del evento

Festa Open Source Girona 2024

### Web del evento

https://festa-opensource.geeks.cat/

### Descripción corta

Fiesta Open Source Girona 2024: charlas, talleres, lightning talks, networking y maratón de PRs para todos los niveles.

### Fecha de inicio

2024-10-19

### Fecha de fin

2024-10-19

### Localización del evento

Casa de Cultura de Girona

### Imagen de portada

https://i.imgur.com/d4Y0EGn.png

### Redes sociales

https://x.com/Geeks_CAT

### Detalles

Únete a la 'Fiesta Open Source Girona 2024', una jornada llena de actividades para todos los niveles y perfiles. Disfruta de charlas inspiradoras, talleres prácticos, lightning talks, networking y una maratón de Pull Requests (PRs). ¡No te pierdas este evento colaborativo y celebra el mundo del software libre con nosotros!

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/festa-open-source-girona

¡Muchas gracias!
