### ISSUE TITLE
LangDev2024

### ISSUE THREAD

**Issue by luciaenriquezbos** [achamorro-dev/eventoswiki#154]
### Nombre o título del evento

LangDev2024

### Web del evento

https://langdevcon.org/

### Descripción corta

LangDev Conference
Seville, 17-19 October 2024.
Where language engineering enthusiasts from both industry and academia come together to discuss the state of the art & state of the practice of language engineering.

### Fecha de inicio

17 Octubre 2024

### Fecha de fin

19 Octubre 2024

### Localización del evento

Sevilla (España)

### Redes sociales

https://x.com/langdev2024, https://www.linkedin.com/in/langdev2024/

### Detalles

**LangDev Conference
Seville, 17-19 October 2024.**

**LangDev** is celebrated on an yearly basis around Europe. It brings together the community working & researching around Language Engineering, MDE, DSLs with a clear focus on showing progress on the state of the art with working tooling. 

**Model Driven Engineering** is gaining traction as one of the Key competences to be developed to foster progress (as recognized by the European Union in different programs).

**Comment by luciaenriquezbos** [comment]
![portada_langdev](https://github.com/user-attachments/assets/136a1567-922f-4e04-9273-3bc18e80a783)

**Comment by achamorro-dev** [comment]
Hola Lucía,

Este evento ya lo teníamos añadido pero he actualizado la imagen de portada con la que me has facilitado y he corregido el mapa de Google Maps.

Puedes ver el evento aquí:

https://eventos.wiki/eventos/2024/langdev

¡Muchas gracias!

**Comment by luciaenriquezbos** [comment]
Gracias a ti Alberto,

Un saludo,
Lucía Enríquez
