### ISSUE TITLE
Añadir nuevo evento: Hackathon NASA Space Apps Zaragoza 2024

### ISSUE THREAD

**Issue by jjpeleato** [achamorro-dev/eventoswiki#155]
### Nombre o título del evento

Hackathon NASA Space Apps Zaragoza 2024

### Web del evento

https://spaceappszgz.github.io/

### Descripción corta

¡Bienvenidos a la hackathon más internacional! Bienvenidos al NASA International Space Apps Challenge Zaragoza 2024, un evento local donde la innovación y la colaboración se unen para abordar los desafíos del futuro 🚀

### Fecha de inicio

2024-10-04T18:00:00.000Z

### Fecha de fin

2024-10-05T18:00:00.000Z

### Localización del evento

ETOPIA, Centro de emprendimiento, innovación y tecnología, Zaragoza, Aragón, España

### Imagen de portada

https://drive.google.com/file/d/1fA3gAuE3I5P8hgLiRUQEom8wo1E4xpPx/view?usp=sharing

### Redes sociales

https://x.com/spaceappszgz

### Detalles

¡Hola, comunidad Hacker! 👋

Os damos la bienvenida a la undécima edición del NASA Space Apps Zaragoza 🚀

Reserva en el calendario los días 4 y 5 de octubre y participa en el hackathon más espacial del año 📅

**¿Qué es el NASA International Space Apps Challenge?**

El NASA International Space Apps Challenge es un evento global que reúne a miles de participantes de todo el mundo en diversas ciudades durante un único fin de semana. Equipos de distintos lugares se unen para enfrentarse a desafíos propuestos por la NASA, y este año, Zaragoza vuelve a ser parte de esta emocionante experiencia 🚀

Space Apps 2023 contó con 13 agencias espaciales internacionales, 24 retos, la participación de 152 países con 402 localizaciones distintas, y un total de 57.999 personas registradas las cuales formaban 8.715 equipos que entregaron 5.556 proyectos.

**El Space Apps 2023 en Zaragoza**

En el evento se formaron 20 equipos con un total de 71 participantes, llegando todos los equipos a la fase de presentación y entrega de premios.

Puedes leer nuestro [artículo resumen en LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:7130094521761021952).

**¿Cuándo y dónde?**

El hackathon (modalidad presencial) comenzará oficialmente el viernes 4 de octubre a las 18:00 y acabará el sábado 5 de octubre a las 13:00 de forma ininterrumpida y con posibilidad de trabajar durante la noche, madrugada y mañana en las aulas, 19 horas para plantear, crear o acabar el proyecto.

A continuación, conoceremos a las entidades colaboradoras y las empresas patrocinadoras, haremos un descanso para comer y se hará la presentación de proyectos de 15:30 a 18:00.

El lugar elegido es el edificio de Etopia. Se encuentra a cinco minutos andando de la estación Delicias (conectado a través de una pasarela) y también se puede llegar con las siguientes líneas de autobús: Ci2, 34 y 51.

**¿Cómo puedo apuntarme?**

El registro de participantes es gratuito y se encuentra abierto. Para poder participar, hay que seguir los siguientes pasos:

1. Formar un equipo de entre 3 y 5 personas.

2. Registrarse en la sede de Zaragoza:

https://www.spaceappschallenge.org/nasa-space-apps-2024/2024-local-events/zaragoza/

3. Elegir un reto e inscribirse con tu equipo:

https://www.spaceappschallenge.org/nasa-space-apps-2024/challenges/

4. Documentar y enviar el proyecto a la NASA y organización antes del sábado 5 de octubre a las 15:30 CEST.

**Premios**

Este año, existirán tres modalidades de premios por equipo.

1️⃣ Premio al mejor proyecto e implementación.

Este galardón no solo incluye un premio de 800 €, sino también un pase directo a la siguiente fase, donde tu proyecto podrá ser revisado por el personal de la NASA y otras agencias espaciales.

2️⃣ Premio a la mejor idea.

La creatividad también es una fuerza poderosa. Con un premio de 300 €, este reconocimiento celebra las ideas sobresalientes. ¡Sólo con una idea y una buena presentación puedes ganar!

3️⃣ Premio voto público.

Premio de 300 € a la idea mejor valorada entre los equipos.

**Patrocinadores**

El evento no sería posible sin nuestros colaboradores y patrocinadores, por eso, desde la organización queremos dar las gracias a todos ellos.

[¡Conoce a los patrocinadores!](https://spaceappszgz.github.io/)

**Mantente informado** 🐦

Podéis seguir todas las noticias desde la cuenta oficial de X (@spaceappsZgz), LinkedIn o a través de la página web, donde iremos publicando información relevante.

Toda la información en: https://spaceappszgz.github.io/

Gracias, la organización NASA Space Apps Zaragoza 2024.

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/hackaton-space-apps-zaragoza

¡Muchas gracias!

**Comment by achamorro-dev** [comment]
Hola @jjpeleato y disculpa si la información que estaba era errónea. Ya debería estar actualizada en la web, cualquier cambio más que necesites no dudes en solicitarlo.

El procedimiento de actualización de contenido hasta ahora podía hacerse mediante PR, modificando directamente el fichero markdown del evento o a través de una issue registrada en el proyecto. Estoy trabajando para que los organizadores de eventos puedan directamente crear/actualizar los eventos desde la web pero hasta entonces...

¡Muchas gracias!

**Comment by jjpeleato** [comment]
Hola, @achamorro-dev.

Así está perfecto, muchas muchas gracias por actualizar el contenido.

Un saludo, José J. Peleato Pradel.
