### ISSUE TITLE
#CodeMeet Madrid:Transforma tu Desarrollo: Seguridad y Mantenibilidad en un Software Descentralizado

### ISSUE THREAD

**Issue by Nattalcual** [achamorro-dev/eventoswiki#156]
### Nombre o título del evento

#CodeMeet Madrid:Transforma tu Desarrollo: Seguridad y Mantenibilidad en un Software Descentralizado

### Web del evento

https://community.codemotion.com/codemotion-espana/meetups/codemeet-madridtransforma-tu-desarrollo-seguridad-y-mantenibilidad-en-un-software-descentralizado

### Descripción corta

El 17 de octubre a las 18:30 h en las oficinas de Openbank, únete a Codemotion para explorar cómo estandarizar, mejorar la seguridad y mantener aplicaciones móviles y microservicios de forma eficiente.

En “#CodeMeet Madrid: Transforma tu Desarrollo - Seguridad y Mantenibilidad en un Software Descentralizado” se profundizará en la transición a arquitecturas modernas. Descubre los beneficios de utilizar el Maven Parent POM en microservicios e iOS, incluyendo la implementación de stacks seguros y mantenibles en entornos críticos como el sector bancario.

Además, habrá una mesa redonda de expertos que abordarán los retos de seguridad y mantenibilidad en un software descentralizado.

### Fecha de inicio

17/10/2024

### Fecha de fin

17/10/2024

### Localización del evento

Openbank Corner

### Imagen de portada

https://drive.google.com/drive/folders/1Nlc9kz9OYkGnm80LR9l8lSM6kmkLBLqJ

### Redes sociales

https://www.linkedin.com/company/codemotion/

### Detalles

El 17 de octubre a las 18:30 h en las oficinas de Openbank, únete a Codemotion para explorar cómo estandarizar, mejorar la seguridad y mantener aplicaciones móviles y microservicios de forma eficiente.

En “#CodeMeet Madrid: Transforma tu Desarrollo - Seguridad y Mantenibilidad en un Software Descentralizado” se profundizará en la transición a arquitecturas modernas. Descubre los beneficios de utilizar el Maven Parent POM en microservicios e iOS, incluyendo la implementación de stacks seguros y mantenibles en entornos críticos como el sector bancario.

Además, habrá una mesa redonda de expertos que abordarán los retos de seguridad y mantenibilidad en un software descentralizado.

¿Por qué asistir?

➡️ Conocimiento técnico: Aprende cómo optimizar el desarrollo con arquitecturas modernas para microservicios y aplicaciones móviles.
➡️ Networking: Conéctate con expertos y profesionales del sector que están transformando el desarrollo de software.
➡️ Innovación: Descubre cómo garantizar builds libres de vulnerabilidades, un reto clave en el entorno bancario.

AGENDA:

➡️ 18:00 Check-In
➡️ 18:15 Bienvenida Openbank & Codemotion
➡️ 18:30 Ponencia: "Transforma tu Desarrollo: Estandarización, Seguridad y Mantenibilidad en Microservicios y Aplicaciones Móviles"
➡️ 19:15 Mesa Redonda: ¿Cómo garantizar la mantenibilidad, estabilidad y homogeneidad en un software descentralizado?
➡️ 19:45 Q&A
➡️ 20:00 Networking

¡No te lo pierdas!

[Apúntate aquí](https://forms.gle/Ao4AGTq6W53tSvwN7)

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/codemotion-codemeet-transforma-tu-desarrollo-seguridad-y-mantenibilidad-en-un-software-descentralizado

¡Muchas gracias!
