### ISSUE TITLE
#CodeMeet: Migrating services at scale: How Ring migrated databases and services without downtime

### ISSUE THREAD

**Issue by Nattalcual** [achamorro-dev/eventoswiki#157]
### Nombre o título del evento

#CodeMeet: Migrating services at scale: How Ring migrated databases and services without downtime

### Web del evento

https://community.codemotion.com/codemotion-espana/meetups/codemeet-migrating

### Descripción corta

¡La tecnología nos une! Este 2 de octubre, únete a nosotros en nuestro emocionante meetup, “Migrating Services at Scale: How Ring Migrated Databases and Services Without Downtime.” Descubre cómo los equipos de Ring en Madrid transformaron su infraestructura, pasando de una configuración monolítica a equipos ágiles de 2 pizzas que gestionan sus propios servicios y mejoran los procesos operativos en la nueva era de sistemas distribuidos.

### Fecha de inicio

02/10/2024

### Fecha de fin

02/10/2024

### Localización del evento

Amazon Madrid Office C. de Ramírez de Prado, 5, Arganzuela, 28045 Madrid, Spain

### Imagen de portada

https://drive.google.com/file/d/1iWdNPs8dhht2EuDPxvZfSkiogwbt9DGn/view?usp=sharing

### Redes sociales

https://www.linkedin.com/company/codemotion/

### Detalles

¡La tecnología nos une! Este 2 de octubre, únete a nosotros en nuestro emocionante meetup, “Migrating Services at Scale: How Ring Migrated Databases and Services Without Downtime.” Descubre cómo los equipos de Ring en Madrid transformaron su infraestructura, pasando de una configuración monolítica a equipos ágiles de 2 pizzas que gestionan sus propios servicios y mejoran los procesos operativos en la nueva era de sistemas distribuidos.

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/codemotion-codemeet-migrating-services-at-scale-how-ring-migrated-databases-and-services-without-downtime

¡Muchas gracias!
