### ISSUE TITLE
GoDigital NEW AGE

### ISSUE THREAD

**Issue by Pablete01** [achamorro-dev/eventoswiki#158]
### Nombre o título del evento

GoDigital NEW AGE

### Web del evento

https://godigital.ticnegocios.es/?utm_source=EMAIL&utm_medium=Campa%C3%B1a&utm_campaign=TIC_GD_2024

### Descripción corta

Sumérgete en la cultura digital y establece conexiones genuinas en un entorno dinámico, donde encontrarás corners temáticos, entrevistas, concursos, contenido de primera calidad, oportunidades de networking y unas vistas impresionantes al mar. 

Un viaje hacia lo desconocido, donde la tecnología se convierte en nuestra guía, desafiándonos a expandir nuestros límites y a imaginar un mundo donde las posibilidades son infinitas. 

### Fecha de inicio

3 de octubre

### Fecha de fin

3 de octubre

### Localización del evento

https://maps.app.goo.gl/Qiur8JQEcWbNmpmr7

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/go-digital-new-age

¡Muchas gracias!
