### ISSUE TITLE
Añadir nuevo evento: 

### ISSUE THREAD

**Issue by arketipo** [achamorro-dev/eventoswiki#159]
### Nombre o título del evento

KaixoOps

### Web del evento

https://enpresadigitala.spri.eus/es/kaixoops/

### Descripción corta

En este encuentro, centrado en la parte operativa de las compañías, distintos profesionales con amplia experiencia en proyectos de gran alcance nos compartirán sus aprendizajes y experiencias sobre la gestión y organización de equipos y relaciones.  

La tecnología es clave para el éxito de un proyecto, pero igualmente lo son la forma en que se gestiona la información, los recursos y las relaciones. 

Está dirigido a empresas y profesionales que se encuentran o han estado en el proceso de escalar sus compañías, enfrentándose al aumento de la complejidad en su organización. 

Esto incluye: la gestión de datos, pagos de licencias, negociación de contratos, elección de tecnologías y procesos, así como las relaciones entre las distintas partes involucradas. A medida que un proyecto crece en alcance y en recursos necesarios, las dificultades también aumentan. Los errores se vuelven más costosos, y aprender de otros profesionales que se han enfrentado a retos similares es muy valioso. 

Cada uno de los profesionales invitados es especialista en áreas como DataOps, FinOps, Liderazgo y Producto. Su visión sobre los desafíos a los que se han enfrentado nos ayudará a no cometer algunos errores y tomar mejores decisiones. Y cómo la IA puede ayudarles en su trabajo. 

### Fecha de inicio

30-10-24

### Fecha de fin

30-10-24

### Localización del evento

https://maps.app.goo.gl/wsLNK4M6a9HXtziu8

### Detalles

Agenda del Evento 

    9:00 – 9:15  Bienvenida e Introducción 

Presentación general del evento y sus objetivos. 

    9:15 – 10:00 El gobierno del dato: cómo estandarizar las métricas de negocio. Patricia Carmona Pulido. 

Cómo la Data Modern Stack nos ayuda a estandarizar métricas y hacerlas más accesibles para que los stakeholders y otras herramientas, como ML, con las que potenciar nuestro negocio 

    10:00 - 10:45 FinOps. Lecciones aprendidas. Victor Martínez Vahillo. 

Introducción de los conceptos básicos y lecciones aprendidas durante la implementación en una gran organización. 

    10:45 - 11:15 Descanso y café
    11:15 - 12:00 {Design/Research/Product} Ops: Gestión del conocimiento en las organizaciones.. Ana Malagón y Goio Telletxea. 

Introducción de conceptos básicos y lecciones aprendidas en la gestión del diseño de productos y servicios en organizaciones de diversa escala. En su charla, hablarán sobre cómo gestionar el conocimiento estableciendo una comunicación clara y precisa entre todas las partes implicadas en un proyecto complejo. 

    12:00 - 12:45 Creando una mini-multinacional. La evolución de Paired hacia una empresa global. Andoni Arroyo 

Te invito a acompañarme en un recorrido por la historia de Paired, donde compartiré cómo transformamos una simple idea en una compañía con presencia internacional. 

Exploraremos en detalle los procesos estratégicos que seguimos, los actores clave que nos acompañaron en el camino, y cómo nos organizamos para afrontar cada fase de crecimiento. 

Hablaremos sobre las herramientas y tecnologías que utilizamos para escalar nuestras operaciones y cómo estas fueron cambiando en cada etapa de nuestra evolución. 

Además, revisaremos anécdotas y lecciones aprendidas que hicieron de este viaje algo único. 

    12:45 – 13:30 Mesa Redonda: Sesión de Preguntas y Clausura del Evento

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/kaixoops

¡Muchas gracias!
