### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by jjimenez-autentia** [achamorro-dev/eventoswiki#16]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: DevFest Spain 2022
- **Descripción corta**: DevFest es una iniciativa promovida a nivel global por Google para apoyar e impulsar a las comunidades tecnológicas
- **Fecha de inicio**: 29/10/2022
- **Fecha de fin**: 29/10/2022
- **Localización del evento**: Valencia
- **Imagen de portada**: 
- **Web del evento**: https://devfest.gdgvalencia.es/
- **Redes sociales**: 
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
✅ Done

https://www.eventos.wiki/eventos/2022/dev-fest-spain
