### ISSUE TITLE
Añadir nuevo meetup KillerSkills: Combatiendo el Burnout en tu equipo

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#160]
### Nombre o título del evento

KillerSkills: Combatiendo el Burnout en tu equipo

### Web del evento

https://lu.ma/qi2b06hf?tk=CsSrlB

### Descripción corta

Iniciamos con nuestros eventos KillerSkills 2024 en Madrid! 🚀

​En esta sesión nos sumergimos en el combate contra el burnout en el equipo. 

​El burnout es un estado de agotamiento físico, mental y emocional causado por el estrés crónico relacionado con el trabajo. A estas alturas es raro que no conozcas un caso de una persona que debido a la presión de cumplir con plazos ajustados, a la carga constante de trabajo y un largo etcétera de situaciones, acaba quemad@ tarde o temprano..

​Aprende a evitarlo, identificando los signos de agotamiento, analizando sus efectos en el rendimiento y la moral. También en descubrir estrategias efectivas para mantener a todos en su mejor forma. 

​El objetivo es practicar cómo enfrentarnos a este desafío, incluso cuando no se ve a simple vista, para equiparte con técnicas que te ayuden a identificar estas situaciones en tu equipo.  

​Compartiendo en un formato 20/80. 

​20% de experiencia destilada: [Jordi Miró Bruix](https://www.linkedin.com/in/jordimirobruix/). fundador de [Ancla life](https://ancla.life/) nos compartirá algunas claves 

​80% de taller práctico: trabajaremos en equipos para identificarlo a través de situaciones reales

### Fecha de inicio

9/10/2024

### Fecha de fin

9/10/2024

### Localización del evento

Jotelulu. c/ Leganitos 47, 4ª planta. 28013 Madrid

### Redes sociales

https://x.com/killerskills_me https://www.linkedin.com/company/killerskills

### Detalles

​En qué va consistir el evento:

​Bienvenida

​Píldora sobre cómo identificar burnout de la mano de [Jordi Miró Bruix](https://www.linkedin.com/in/jordimirobruix/)

​Práctica en equipo

​Compartir aprendizajes

​Cierre

​Networking

​​​Por supuesto tendremos comida y bebida 🍕🍺 patrocinada por [Jotelulu](https://jotelulu.com/) para pasar un rato divertido y entretenido haciendo networking.

​​​​Este evento está dirigido a managers y gestores de equipo, proactivos y curiosos que buscan resolver los problemas y realizar una gestión de equipos sana con mayor impacto.

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/killerskills-combatiendo-el-burnout-en-tu-equipo

¡Muchas gracias!
