### ISSUE TITLE
Granada Gaming Festival

### ISSUE THREAD

**Issue by nachocabrero** [achamorro-dev/eventoswiki#161]
### Nombre o título del evento

Granada Gaming Festival 2025

### Web del evento

https://www.granadagaming.com

### Descripción corta

Festival divulgativo y de ocio, pero también con profesionales del sector y atención a estudios independientes de desarrollo de videojuegos.

### Fecha de inicio

26/04/2025

### Fecha de fin

27/04/2025

### Localización del evento

FERMASA, Granada

### Redes sociales

@granadagaming

**Comment by nachocabrero** [comment]
Aun no está disponible el cartel, dejo aquí el logo por si sirve:
https://www.granadagaming.com/wp-content/uploads/sites/2/2024/07/logo-granadagaming-gg-2025-vector-blanco-500px.png

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Muchas gracias Nacho, al final he cogido el cartel del canal de Youtube que, aunque no se ve completo, tiene fondo. Puedes ver el evento por aquí:

https://www.eventos.wiki/eventos/2025/granada-gaming

¡Muchas gracias!

**Comment by nachocabrero** [comment]
Gracias a ti!!El 18 oct 2024, a las 7:07, Alberto Chamorro ***@***.***> escribió:﻿
✅ ¡Añadido! Muchas gracias Nacho, al final he cogido el cartel del canal de Youtube que, aunque no se ve completo, tiene fondo. Puedes ver el evento por aquí:
https://www.eventos.wiki/eventos/2025/granada-gaming
¡Muchas gracias!
