### ISSUE TITLE
Añadir nuevo evento: Meetups de Gofigeeks

### ISSUE THREAD

**Issue by Sstark97** [achamorro-dev/eventoswiki#162]
En gran canaria se hace un meetup bastante buen todos los meses, se llama Gofigeeks. Este mes tenemos un pedazo de taller de Codium 😁

https://meetu.ps/e/Nycdr/Tp3F7/i

**Comment by Sstark97** [comment]
Podría encargarme sin problema!

**Comment by achamorro-dev** [comment]
Hola Aitor,

PR integrada, ¡¡muchas gracias!!

**Comment by Sstark97** [comment]
Muchas gracias a ti! Seguiré actualizando los próximos Meetups que vayan saliendo 🫶
