### ISSUE TITLE
GitHub Universe 2024 - Watch Party - Madrid - 29/10/2024

### ISSUE THREAD

**Issue by svg153** [achamorro-dev/eventoswiki#165]
### Nombre o título del evento

"GitHub Universe 2024 - Watch Party"

### Web del evento

https://www.meetup.com/comunidad-github-spain/events/304075362/

### Descripción corta

Haremos una Watch Party para ver evento de GitHub Universe, es el evento más grande de GitHub del año, donde se presentan todas las novedades de la plataforma y ecosistema, desde cambios en los planes y precios, hasta las novedades de GitHub Copilot. Nos reuniremos para verlo en directo, compartir ideas y seguir aprendiendo juntos

Aquí tienes los detalles del evento:

🗓️ Fecha: 29 de octubre de 2024
🕒 Hora: 18:00 - 20:00
📍 Lugar: Google Campus Madrid
🎟️ Entrada gratuita

Para más info ve a la web del evento.

### Fecha de inicio

29/10/2024

### Fecha de fin

29/10/2024

### Localización del evento

Google Campus Madrid

### Imagen de portada

https://secure.meetupstatic.com/photos/event/8/b/0/b/600_524135595.webp?w=384

### Redes sociales

https://twitter.com/GithubCommSpain

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/github-universe-2024-watch-party

¡Muchas gracias!
