### ISSUE TITLE
Añadir nuevo evento: Valencia.rb Ruby meetup (Ruby Europe Initiative)

### ISSUE THREAD

**Issue by esti** [achamorro-dev/eventoswiki#169]
### Nombre o título del evento

Ruby Europe Initiative & Kick-off

### Web del evento

https://valenciarb.org/meetings/2024-11-06-ruby-europe-initiative-kickoff/

### Descripción corta

Valencia.rb vuelve a re-inagurarse tras casi 5 años de inactividad.

Nuestro evento de re-inaguración no podría estar mejor! La iniciativa [Ruby Europe](https://rubyeurope.com/) nos ha dado la motivación que necesitabamos para volver a hablar de ese lenguaje que tanto nos apasiona Ruby.

### Fecha de inicio

5/11/2024

### Fecha de fin

5/11/2024

### Localización del evento

Oficinas New Work Valencia

### Redes sociales

https://www.twitter.com/valenciarb

### Detalles

En nuestra siguiente reunión tenemos el placer de contar con [Rosa Gutiérrez](https://rosa.codes/), programadora en [37Signals](https://37signals.com/) (la compañia detras de [Ruby on Rails](https://rubyonrails.org/) y productos como [Basecamp](https://basecamp.com/) y [Hey](https://www.hey.com/)).

### Agenda

**Beyond Meetups: Creating Ruby Ecosystem**

“Discover how Ruby Europe is building a stronger Ruby ecosystem. Learn how this organization supports community development and how you can be part of shaping its future.”

[Mariusz Kozieł](https://x.com/KozieMariusz)

**Solid Queue internals, externals and all the things in between**

“We’ve used Resque and Redis to run background jobs in multiple apps for many years at 37signals. However, performance, reliability, and our own apps’ idiosyncrasies led us to use a lot of different gems, some developed by us, some forked or patched to address our struggles. After multiple war stories with background jobs, looking at our increasingly complex setup, we wanted something we could use out-of-the-box without having to port our collection of hacks to every new app and with fewer moving pieces. After exploring existing alternatives, we decided to build our own and aim to make it the default for Rails 8. In this talk, I’ll present Solid Queue, explain some of the problems we had over the years, how we designed Solid Queue to address them, and all the Fun™ we had doing that.”

[Rosa Gutiérrez](https://rosa.codes/)

**My LLM is smarter than yours - the Ruby way to build RAG applications**

“The talk will cover how to use Large Language Models (LLMs) and Embeddings to build applications that reason about internal (in-house) knowledge. How to make apps smarter and more context-aware. And all that in the context of Ruby (and a bit of Rails) tools and solutions”

[Pawel Strzalkowski](https://github.com/pstrzalk)

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/valenciarb-ruby-europe-initiative-kickoff

¡Muchas gracias!

**Comment by esti** [comment]
¡Hola!

El evento se ha postpuesto sin fecha concreta por las consecuencias de la DANA. Este es el mensaje que han puesto en la web.

---

‼️ Posponemos el proximo evento ‼️

Desde la organización de Valencia.rb hemos decidido posponer el proximo Meetup del día 6 de Noviembre.

Como comunidad nuestra prioridad es ofrecer un evento de calidad y un espacio seguro y a día de hoy no podemos garantizar que se pueda asistir al evento sin ningún tipo de riesgo tanto como para los ponentes como asistentes.

Al mismo tiempo, nos solidarizamos con las familias, amigos y compañeros afectados por la DANA.

Si puedes ayudar a la gente afectada por DANA dona en [la Cruz Roja](https://cercadeti.cruzroja.es/ayudaafectadosinundacionesdana) o [Caritas](https://www.caritas.es/emergencias/graves-inundaciones/).

---

¿Puedes incorporar esto en el evento? ¡Muchas gracias!

**Comment by achamorro-dev** [comment]
Hola @est

**Comment by achamorro-dev** [comment]
Toda la razón @esti, ya está el contenido corregido.

Disculpa las molestias 🙏

**Comment by esti** [comment]
Para nada @achamorro-dev!!

Muchas gracias por mantener el wiki!!
