### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by z0r3f** [achamorro-dev/eventoswiki#17]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: Codemotion Online Tech Conference - Spanish Edition
- **Descripción corta**: 
- **Fecha de inicio**: 22/11/2022
- **Fecha de fin**: 23/11/2022
- **Localización del evento**: Online & Talent Garden, Calle Juan de Mariana 15, Madrid, de 14:30 a 18:30
- **Imagen de portada**:
- **Web del evento**: https://events.codemotion.com/conferences/online/2022/online-tech-conference-2022-spanish-edition-autumn
- **Redes sociales**: [Twitter](https://twitter.com/CodemotionIT/)
- **Detalles**(esta información aparecerá como contenido del evento):
Embárcate en un viaje para descubrir las últimas tendencias en backend, frontend, devops, IA/ML y mucho más en dos días de charlas, keynotes y paneles.
La Codemotion Tech Conference es una cita obligada para las y los profesionales del mundo IT en búsqueda de novedades sobre las últimas tecnologías, charlas inspiracionales y actividades.

**Comment by achamorro-dev** [comment]
✅ Done

https://www.eventos.wiki/eventos/2022/codemotion-spain
