### ISSUE TITLE
Añadir nuevo evento: Barcelona.rb Ruby meetup

### ISSUE THREAD

**Issue by esti** [achamorro-dev/eventoswiki#170]
### Nombre o título del evento

Barcelona.rb november meetup

### Web del evento

https://www.meetup.com/barcelona-rb/events/304030335

### Descripción corta

This meetup marks the beginning of an exciting journey across Spain, connecting Ruby enthusiasts in Barcelona, Valencia, and Madrid. Be part of this historic moment in the Spanish Ruby community!

### Fecha de inicio

05/11/2024

### Fecha de fin

05/11/2024

### Localización del evento

Loft de Gràcial, C. de Montmany, 30, Barcelona

### Redes sociales

https://es.linkedin.com/company/barcelona-rb

### Agenda

🎙️ Mariusz Kozieł - Beyond Meetups: Creating Ruby Ecosystem
🎙️ Roman Samoilov - Modernising Ruby Systems with Rage
🎙️ Genar Trias Ortiz - Life beyond MVC: scaling Rails monolith for hundreds of developers
🔥 Networking!

**The Spain Triangle Project**

This meetup is part of the larger Spain Triangle Project, an initiative by Ruby Europe to strengthen the Ruby community in Spain. Don't miss the other events:

    Barcelona.rb on November 5th
    Valencia.rb on November 6th: [Valencia.rb](https://www.meetup.com/vlctechhub/events/304025350/)
    Madrid.rb on November 7th: [Madrid.rb](https://www.madridrb.com/events/ruby-europe-madrid-1046)

🚂 Join the Ruby Train! We're inviting a group of enthusiasts to travel together to all three events. More Ruby, more networking, more fun! Train group: [Google Form](https://forms.gle/aRyoxWaji5s55F1e6)

**About Ruby Europe**

Ruby Europe is uniting Ruby enthusiasts across the continent to build a thriving community. Join us on [Discord](https://discord.gg/VQpDWPpBZe) and visit [rubyeurope.com](https://rubyeurope.com/) to learn more!
Join us for an evening of learning, networking, and celebrating Ruby. Let's kickstart this Ruby revolution together!

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/barcelonarb-ruby-meetup-november

¡Muchas gracias!
