### ISSUE TITLE
Añadir nuevo evento: Madrid.rb Ruby meetup

### ISSUE THREAD

**Issue by esti** [achamorro-dev/eventoswiki#171]
### Nombre o título del evento

Madrid.rb November Ruby meetup (Ruby Europe Initiative)

### Web del evento

https://www.madridrb.com/events/ruby-europe-madrid-1046

### Descripción corta

Get ready for an unforgettable Ruby meetup as we wrap up the Ruby Europe: Spain Triangle Project - a pioneering initiative to unite and invigorate the Ruby community across Spain!

### Fecha de inicio

07/11/2024

### Fecha de fin

07/11/2024

### Localización del evento

Oficinas Lingokids - Madrid

### Redes sociales

https://twitter.com/madridrb

### Detalles

As the final stop in our Ruby journey across Spain, this meetup is your chance to be part of a historic moment. Let's make Madrid a beacon for Ruby developers!

### Agenda

    🎤 Mariusz Kozieł - 'Beyond Meetups: Creating Ruby Ecosystem’
    🎤 Egor Iskrenkov - ‘Code review automation: getting rid of "you forgot to..." comments’
    🎤 Chris Hasiński - ‘Next token! (Or how to work with LLMs)’

**The Spain Triangle Project**

We're thrilled to host the final event of the Spain Triangle Project, an initiative by Ruby Europe. Catch up on what you missed:

    [Barcelona.rb on November 5th](https://www.meetup.com/barcelona-rb/events/304030335)
    [Valencia.rb on November 6th](https://www.meetup.com/vlctechhub/events/304025350)
    Madrid.rb on November 7th

🚂 Join the Ruby Train! We're inviting a group of enthusiasts to travel together to all three events. More Ruby, more networking, more fun! Train group: https://forms.gle/aRyoxWaji5s55F1e6

**About Ruby Europe**

Ruby Europe is uniting Ruby enthusiasts across the continent to build a thriving community. Join us on [Discord](https://discord.gg/VQpDWPpBZe) and visit [rubyeurope.com](https://rubyeurope.com/) to learn more!

Join us in celebrating Ruby, forging new connections, and charting the course for Spain's Ruby future!

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/madridrb-ruby-europe-madrid

¡Muchas gracias!
