### ISSUE TITLE
Añadir nuevo evento: Gofigeeks

### ISSUE THREAD

**Issue by Sstark97** [achamorro-dev/eventoswiki#172]
### Nombre o título del evento

Global Day of Coderetreat 2024

### Web del evento

https://www.meetup.com/gofigeeks/events/304286126/?eventOrigin=group_upcoming_events

### Descripción corta

Para quienes no lo conozcan: [Coderetreat](https://www.coderetreat.org/) es un esfuerzo voluntario coordinado a nivel mundial para poner en práctica y mejorar nuestras habilidades en el desarrollo de software. Todo esto se realiza en un ambiente distendido, donde tendremos la oportunidad de centrarnos en practicar, sin preocuparnos por el tiempo o la presión del día a día y sin miedo a cometer errores. El objetivo no es terminar, sino disfrutar, y seguir las mejores prácticas posibles.

### Fecha de inicio

9 de Noviembre de 9:00(Hora canarias)

### Fecha de fin

9 de Noviembre de 17:00 (Hora canarias)

### Localización del evento

Gran Canaria

### Imagen de portada

https://secure.meetupstatic.com/photos/event/1/5/9/600_524400345.webp

### Redes sociales

https://www.linkedin.com/company/gofigeeks

## Details
¡Nos complace anunciar que este año tenemos el orgullo de poder celebrar la edición de **Global Day of Coderetreat 2024**!

Para quienes no lo conozcan: [Coderetreat](https://www.coderetreat.org/) es un esfuerzo voluntario coordinado a nivel mundial para poner en práctica y mejorar nuestras habilidades en el desarrollo de software. Todo esto se realiza en un ambiente distendido, donde tendremos la oportunidad de centrarnos en practicar, sin preocuparnos por el tiempo o la presión del día a día y sin miedo a cometer errores. El objetivo no es terminar, sino disfrutar, y seguir las mejores prácticas posibles.

### ¿En qué consiste?
Dicha actividad consiste en desarrollar la kata The Game of Life haciendo pair programming y siguiendo la metodología del TDD. Se dividirán en 5 sesiones de 45 minutos, rotando en cada sesión con una pareja diferente y eligiendo el lenguaje con el que se quiera trabajar.

Las personas que faciliten la sesión introducirán pequeños retos o restricciones para que las personas participantes planteen el problema de forma diferente y así poder practicar distintas metodologías.

### ¿Quién puede participar?
Cualquier persona con ganas de aprender y pasar un día diferente! La sesión está dirigida tanto a estudiantes, como a developers con experiencia. Haremos una breve introducción al TDD y algunas buenas prácticas para que tengas por dónde empezar.

### Detalles y horario del evento
El evento empezará a las 9:00, donde habrá una introducción y tendremos un pequeño desayuno provisto por la organización.

A la **13:30** haremos una parada para comer.
Pueden traer su comida o salir a comer a cualquiera de los locales que estén por la zona.

Volveremos a las **14:45** para seguir con las sesiones restantes, para finalmente hacer el cierre a las **17:00**.

### Requisitos:

- Portátil con tu entorno preparado para programar en tus lenguajes preferidos. Si no tienes portatil no hay problema, ya que haremos parejas y esperamos que hayan portátiles para todas y todos.
Te esperamos!! 🎉🤗

📅 9 de Noviembre 2024
⏰ 09:00 hasta 17:00
📍 Triana Coworking, C. Bravo Murillo, 34, Las Palmas

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/gofigeeks-global-day-of-coderetreat

¡Muchas gracias!
