### ISSUE TITLE
Añadir nuevo evento: KillerSkills: Level up: Eleva tu influencia

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#173]
### Nombre o título del evento

KillerSkills: Level up: Eleva tu influencia

### Web del evento

https://lu.ma/gh1q74bj?tk=NGQUH9

### Descripción corta

Nuevo evento de KillerSkills en Madrid! 🚀

​Seguimos trabajando duro en el combate para mejorar nuestras KillerSkills. A petición vuestra continuamos con la influencia. 

​La influencia nos permite conceptualizar y convencer a otros, también liderar activamente garantizando que las nuevas ideas se adopten y se implementen eficazmente.

​En el día a día nos enfrentamos a muchas situaciones donde tenemos que tratar de convencer a otros -que no manipular-. Cuando vemos que no nos siguen o recibimos NOes, nos provoca mucha frustración y empezamos a preguntarnos:

​¿No ven lo que yo veo?

​¿No lo habré explicado bien?

​¿He hecho algo mal?

​El objetivo es practicar cómo enfrentarnos a este desafío para equiparte con técnicas que te ayuden a tener mayor impacto y reducir la fricción que generan estas conversaciones..  

​Lo haremos a través de un formato 20/80:

​20% de experiencia destilada: nos acompaña [Samuel Fuentes](https://www.linkedin.com/in/samuelfuentes/) co-founder y CPTO de [Ontruck](https://www.ontruck.com/en/transport-software) que compartirá algunas claves 

​80% de taller práctico: trabajaremos en equipos para practicar la influencia simulando situaciones reales

​¿Qué va a pasar?

​Bienvenida

​Píldora sobre cómo podemos elevar la influencia de la mano de [Samuel Fuentes](https://www.linkedin.com/in/samuelfuentes/)

​Practicaremos en grupos a través de escenarios reales

​Compartiremos aprendizajes

​Cierre

​Disfrutaremos de un rato divertido haciendo networking con la comida 🍕 y bebida 🍺 patrocinada por[ Jotelulu](https://jotelulu.com/) en sus oficinas.

​​​​Este evento está dirigido a managers y gestores de equipo, proactivos y curiosos que buscan resolver los problemas y realizar una gestión de equipos sana con mayor impacto.

​¡No pierdas esta oportunidad para aprender está [KillerSkill](https://killerskills.me/), mejorar tus habilidades de liderazgo y apoyar a tu equipo!

### Fecha de inicio

19/11/2024

### Fecha de fin

19/11/2024

### Localización del evento

JOTELULU. C. de Leganitos, 47, 4º, Centro, 28013 Madrid

### Imagen de portada

https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=2,background=white,quality=75,width=400,height=400/event-covers/id/81a439bc-0f7c-4be3-afee-f8963a64c5db

### Redes sociales

https://x.com/killerskills_me https://www.linkedin.com/company/killerskills

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/killerskills-level-up-eleva-tu-influencia

¡Muchas gracias!
