### ISSUE TITLE
Añadir nuevo evento: Asturias Software Crafters

### ISSUE THREAD

**Issue by Llambi** [achamorro-dev/eventoswiki#174]
### Nombre o título del evento

Asturias Software Crafters - Noviembre: Ops → DevOps → PlatformEngineering

### Web del evento

https://saraos.tech/@asturias-software-crafters/events/asturias-software-crafters-noviembre-ops-devops-platformengineering-wji78dq4cfrob7fvlzkc3

### Descripción corta

En esta sesión tendremos la participación de [**Ramiro Álvarez Fernández**](https://ramiroalvfer.dev/) _Staff Platform Engineer_ en [Empathy.co](https://www.empathy.co/) y _cofundador_ de [Resizes](https://resiz.es/). En ella hablaremos  sobre la transformación de operaciones (**Ops**) a desarrollo de operaciones (**DevOps**) y a su vez a **PlatformEngineering** desde su experiencia, y de forma que aquellas personas que se animen a asistir puedan entender en qué estado de madurez se encuentran, cómo pueden evolucionar y ver mejoras/problemas en cada etapa.

### Fecha de inicio

22/11/2024 18:30

### Fecha de fin

22/11/2024 20:30

### Localización del evento

El Talud de la Ería - C. Virgilio Palacio, 1, 33013 Oviedo, Asturias

### Imagen de portada

https://github.com/user-attachments/assets/d1aea74a-8f33-405a-a88b-6a74100bd400

### Redes sociales

https://linktr.ee/asturiaswcraft

### Detalles

![Portada ASC Noviembre](https://github.com/user-attachments/assets/d1aea74a-8f33-405a-a88b-6a74100bd400)

## Estrenemos el otoño 🍁

Volvemos a **Oviedo** 🏓, y una vez más nos veremos en el espacio [**Talud**](https://oviedoemprende.es/espacios/talud-eria/).

En esta sesión tendremos la participación de [**Ramiro Álvarez Fernández**](https://ramiroalvfer.dev/) _Staff Platform Engineer_ en [Empathy.co](https://www.empathy.co/) y _cofundador_ de [Resizes](https://resiz.es/). En ella hablaremos  sobre la transformación de operaciones (**Ops**) a desarrollo de operaciones (**DevOps**) y a su vez a **PlatformEngineering** desde su experiencia, y de forma que aquellas personas que se animen a asistir puedan entender en qué estado de madurez se encuentran, cómo pueden evolucionar y ver mejoras/problemas en cada etapa.

## Notas 🗒️
Si vienes en coche, puedes aparcar fácilmente:

- [Parking Estadio Carlos Tartiere](https://maps.app.goo.gl/8eFe5GeJJjk5AfmB7)

Si es tu primera vez en el Talud de la Ería, [aquí tienes como entrar](https://oviedoemprende.es/espacios/talud-eria/) tanto desde el Parking del Estadio como si vienes andando.

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/asturias-software-crafters-noviembre-ops-a-devops-a-platformengineering

¡Muchas gracias!
