### ISSUE TITLE
Añadir nuevo evento: #CodeMeet Barcelona: Qui no té tecnologia, el gat pentina

### ISSUE THREAD

**Issue by Nattalcual** [achamorro-dev/eventoswiki#176]
### Nombre o título del evento

#CodeMeet Barcelona: Qui no té tecnologia, el gat pentina

### Web del evento

https://codemo.tech/Meetup-BC

### Descripción corta

Este 28 de noviembre, únete a Codemotion y a la comunidad de MuleSoft para un nuevo meetup en las oficinas de Adevinta. Disfrutaremos de 6 charlas inspiradoras en un entorno de comunidad tech, donde los ponentes compartirán sus conocimientos, y cerraremos con networking y un picoteo. Este evento será híbrido, ¡puedes asistir tanto online como en persona en Adevinta!

### Fecha de inicio

28/11/2024

### Fecha de fin

28/11/2024

### Localización del evento

Adevinta Carrer de la Ciutat de Granada, 150, Sant Martí, 08018 Barcelona, Spain

### Imagen de portada

https://drive.google.com/drive/folders/1UiG7Kj979K_9NVBB2e7yGJZhvqPKrrEJ

### Redes sociales

https://www.linkedin.com/company/codemotion/

### Detalles

Este 28 de noviembre, únete a Codemotion y a la comunidad de MuleSoft para un nuevo meetup en las oficinas de Adevinta. Disfrutaremos de 6 charlas inspiradoras en un entorno de comunidad tech, donde los ponentes compartirán sus conocimientos, y cerraremos con networking y un picoteo. Este evento será híbrido, ¡puedes asistir tanto online como en persona en Adevinta!

📅 Agenda del evento

➡️ 6:00 PM - Bienvenida y presentación de comunidades
➡️ 6:20 PM - Ángel Paredes: Prácticas para User-First API Design
➡️ 6:40 PM - Mark Boyd: Gobernanza de APIs
➡️ 7:00 PM - Jorge Lebrato: ¿Por qué la Liga de la Justicia no necesita MuleSoft?
➡️ 7:20 PM - Sergio Acebes: Construye tu producto digital y mantenlo a salvo de ataques
➡️ 7:40 PM - Laura Marqués: Impulsando la estrategia de datos en B2B: Equipos, APIs y toma de decisiones
➡️ 8:00 PM - Noelia Torres: Rompiendo Códigos: Inclusión y Talento Femenino en el sector Tech
➡️ 8:20 PM - Sorteo y despedida online
➡️ 8:30 PM - Networking presencial

📢 Ponentes y Charlas

➡️ Ángel Paredes - Prácticas para User-First API Design

La clave en el desarrollo de productos es no perder de vista al usuario. En esta charla, exploraremos cómo diseñar APIs que no solo expongan datos, sino que mejoren la experiencia de usuario desde el diseño hasta la implementación.

➡️ Mark Boyd - Gobernanza de APIs

Cuando la gobernanza de APIs se hace bien, facilita la creación de productos, pero si se maneja mal, puede generar cuellos de botella. En esta charla, Mark compartirá cómo implementar procesos ágiles de gobernanza de API para mejorar la experiencia de los desarrolladores.

➡️ Jorge Lebrato - ¿Por qué la Liga de la Justicia no necesita MuleSoft?

Exploraremos de manera divertida la importancia de contar con una herramienta potente como MuleSoft en grandes organizaciones y sistemas complejos.

➡️ Sergio Acebes - Construye tu producto digital y mantenlo a salvo de ataques

Aprende a construir y mantener un producto digital mediante APIs, enfrentando retos como la seguridad, escalabilidad y adopción de usuarios, todo en un contexto de juego estratégico.

➡️ Laura Marqués - Impulsando la estrategia de datos en B2B: Equipos, APIs y toma de decisiones

Descubre cómo una estrategia de datos bien diseñada puede transformar las operaciones en el entorno B2B, y cómo los equipos de data analytics y data engineering juegan un rol clave en este proceso.

➡️ Noelia Torres - Rompiendo Códigos: Inclusión y Talento Femenino en el sector Tech

En esta charla, conoceremos cómo Factoría F5 está promoviendo la inclusión y diversidad en el sector tecnológico, con un enfoque especial en el programa FemCoders y su impacto en la reducción de la brecha de género digital.

¡Nos vemos en Barcelona!

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/codemotion-codemeet-barcelona-qui-no-te-tecnologia-el-gat-pentina

¡Muchas gracias!
