### ISSUE TITLE
#Codemeet: Responsible by Design: Ética y usabilidad en IA

### ISSUE THREAD

**Issue by Nattalcual** [achamorro-dev/eventoswiki#177]
### Nombre o título del evento

#Codemeet: Responsible by Design: Ética y usabilidad en IA

### Web del evento

https://codemo.tech/IA-Evenbrite

### Descripción corta

Este 21 de noviembre Codemotion te invita a un meetup donde hablaremos sobre tecnología ética. En #Codemeet: "Responsible by Design: Ética y Usabilidad en IA", exploraremos cómo diseñar y aplicar IA de manera responsable para lograr un impacto positivo.

### Fecha de inicio

21/11/2024

### Fecha de fin

21/11/2024

### Localización del evento

Accenture Madrid P.º de la Castellana, 85, Tetuán, 28046 Madrid, Spain

### Imagen de portada

https://drive.google.com/file/d/1gEgHB3NSsfTLvKKemogzkjeZCm-36j1W/view?usp=sharing

### Redes sociales

https://www.linkedin.com/company/codemotion/

### Detalles

Este 21 de noviembre Codemotion te invita a un meetup donde hablaremos sobre tecnología ética. En #Codemeet: "Responsible by Design: Ética y Usabilidad en IA", exploraremos cómo diseñar y aplicar IA de manera responsable para lograr un impacto positivo.

[Link aquí
](https://codemo.tech/IA-Evenbrite)
➡️ Ponentes:

Emma Galindo: Accenture Responsible AI Associate Director

Ha desarrollado su carrera profesional como directiva de diversas compañías multinacionales del sector de la tecnológica, especializándose en Consultoría Estratégica, Operaciones, Rendimiento, CRM, Servicios Financieros y Transformación Digital, así como gestión del Customer Journey, desarrollo de negocios y planificación empresarial. Desde diciembre de 2023 lidera el área de Responsible AI de Accenture en España

José Bernal: Accenture AI LLM Technology Architecture Senior Manager

Con más de 25 años de experiencia en el mundo tecnológico, ha dedicado los últimos años a la Inteligencia Artificial, explorando desde sus aplicaciones en neurociencia al desarrollo de la IA Generativa. Desde hace 10 desempeña estas tareas en Accenture, donde actualmente lidera el área de IA en sus Centros de Tecnología Avanzada.

¿Por qué asistir?

➡️ Conocimiento práctico: Aprende de los expertos cómo implementar IA responsable desde su diseño, respetando la privacidad y la seguridad de los datos.
➡️ Networking profesional: Conecta con líderes del sector y otros entusiastas de la IA ética.
➡️ Innovación con propósito: Descubre los principios y metodologías de diseño responsable para una IA que beneficia a todos.

AGENDA

18:45 - Check-In
19:00 - 19:10 - Bienvenida de Accenture & Codemotion
19:10 - 20:10 - "Hacia una IA Responsable: Estrategia y Casos de uso" por Emma Galindo y José Bernal
20:10 - 20:25 - Q&A
20:25 - 21:30 - Networking

📍 Lugar: Accenture Madrid, Paseo de la Castellana, 85

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/codemotion-codemeet-madrid-responsible-by-design-etica-y-usabilidad-en-ia

¡Muchas gracias!
