### ISSUE TITLE
Añadir nuevo evento: TRGCON 25

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#178]
### Nombre o título del evento

TRGCON 25

### Web del evento

https://www.trgcon.com/

### Descripción corta

Personas, tecnología y negocio.
La TRG es una conferencia sobre diseño, construcción y comercialización de servicios digitales que nace alrededor de la heterogénea Comunidad de suscriptores de La Bonilista, la newsletter semanal sobre emprendimiento tecnológico escrita por David Bonilla.

Es ante todo, un punto de encuentro para gente que «hace cosas» alrededor del software, la innovación tecnológica e Internet: desarrolladores, diseñadores, inversores, comerciales, gente de marketing o soporte, administradores de sistemas o recruiters. Nadie sobra y todos son bienvenidos.

Se organiza cuidando cada detalle de forma enfermiza —desde las acreditaciones hasta la oferta gastronómica— para intentar transformar la asistencia en una experiencia y aportar el mayor valor posible a asistentes, ponentes y patrocinadores.

### Fecha de inicio

17/10/2025

### Fecha de fin

19/10/2025

### Localización del evento

La Nave. C. Cifuentes, 5, Villaverde, 28021 Madrid

### Redes sociales

https://twitter.com/tarugoconf https://tarugoconf.slack.com/

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2025/trgcon

¡Muchas gracias!
