### ISSUE TITLE
Añadir nuevo evento: Flutter Malaga DevParty 2.0

### ISSUE THREAD

**Issue by Beelzenef** [achamorro-dev/eventoswiki#179]
### Nombre o título del evento

Flutter Malaga DevParty 2.0 🎉

### Web del evento

https://www.meetup.com/flutter-malaga/events/303644498

### Descripción corta

🥳 ¡Vuelve la Flutter Málaga DevParty! 🎈

Tras el gran éxito del año pasado con más de 50 asistentes, nos preparamos para otra edición inolvidable. El 22 de noviembre nos reunimos de nuevo para disfrutar de dos charlas inspiradoras, un taller interactivo y sorteos con increíbles premios. Además, no faltará el picoteo para acompañar una tarde llena de aprendizaje, comunidad y buen ambiente. ¡Únete y sé parte de esta experiencia única con Flutter en Málaga!

### Fecha de inicio

22/11/2024

### Fecha de fin

22/11/2024

### Localización del evento

Edificio El Rayo Verde (THE GREEN RAY), Avenida Louis Pasteur, 47, Málaga

### Imagen de portada

https://secure.meetupstatic.com/photos/event/3/0/4/8/600_524112360.webp?w=384

### Redes sociales

https://twitter.com/fluttermalaga

### Detalles

Un evento con tres charlas, en inglés y español, para hablar de diferentes temas alrededor del framework Flutter. También cuenta con un taller interactivo para principiantes.

**Agenda:**

16:00-16:45 👋🏼 Presentaciones
16:45-17:10 🎤 Charla 1: Tests with Flutter, how to start (🇬🇧, Teodor)
17:10-17:15 Descanso
17:15-17:40 🎤 Charla 2: Accesibilidad a la europea (🇪🇸, Elena)
17:40-17:45 Descanso
17:45-18:00 🎤 Charla 3: Más Allá de la Pantalla: Flutter, Dart e IoT (🇪🇸, Gaby)
18:00-18:10 Descanso
18:10-19:25 🧑🏻‍💻 Workshop: Construye tu app en Flutter (🇪🇸, Daniel)
19:25-20:00 🎉 Networking, sorteos y premios

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/flutter-malaga-devparty-2

¡Muchas gracias!
