### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by pablosirera** [achamorro-dev/eventoswiki#18]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: BilboStack;
- **Descripción corta**: 11ª Edición de la cita tecnológica anual más esperada en Bilbao
- **Fecha de inicio**: 28/01/2023
- **Fecha de fin**: 28/01/2023
- **Localización del evento**: Palacio Euskalduna 4 Abandoibarra Etorbidea 48011 Bilbo
- **Imagen de portada**: 
![image](https://user-images.githubusercontent.com/25353031/201040957-aec6ef3a-c825-4896-b532-e49db74a976e.png)
- **Web del evento**: https://bilbostack.com/
- **Redes sociales**: https://twitter.com/BilboStack
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
✅ Done

https://www.eventos.wiki/eventos/2023/bilbostack
