### ISSUE TITLE
Añadir nuevo evento: Lareira Conf

### ISSUE THREAD

**Issue by anawolfdev** [achamorro-dev/eventoswiki#180]
### Nombre o título del evento

Lareira Conf

### Web del evento

https://www.lareiraconf.es/

### Descripción corta

Punto de encuentro para todos los apasionados por la tecnología, cuyo objetivo es reunir los miembros de las distintas comunidades técnicas y a otros desarrolladores, estudiantes y profesionales IT en un espacio donde puedan aprender, compartir experiencias y conectar con otros lareireiros.

### Fecha de inicio

22-03-25

### Fecha de fin

22-03-25

### Localización del evento

Paraninfo UDC A Coruña

### Redes sociales

https://www.linkedin.com/in/lareira-conf-coru%C3%B1a-20313a337/

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2025/lareira-conf

¡Muchas gracias!
