### ISSUE TITLE
Añadir nuevo evento: 

### ISSUE THREAD

**Issue by aquiestaThai** [achamorro-dev/eventoswiki#181]
### Nombre o título del evento

Event Modeling: ¡Manos a la obra!

### Web del evento

https://lu.ma/sxcdai7r

### Descripción corta

​¡Volvemos con otro taller "manos a la obra" de la comunidad #CoMo!

​Ven y pon en práctica lo aprendido en nuestro último encuentro, trabajando en equipo para modelar un escenario real con [Event Modeling](https://eventmodeling.org/posts/what-is-event-modeling/). 

​Creada por [Adam Dymitruk](https://www.linkedin.com/in/eventmodeling/) es un método que se enfoca en capturar y describir el flujo de eventos en un sistema. A través de este enfoque, los equipos pueden entender cómo las entidades del sistema interactúan a lo largo del tiempo, proporcionando una visión clara y completa del comportamiento del sistema.

​Ya sea como domain expert, facilitador o modeler, trabajarás con tus compañeros en la modelización. Finalizaremos el taller con una puesta en común en la que compartiremos impresiones y lecciones aprendidas.

​Y si no pudiste asistir a la introducción a la técnica con [Alexandra Moxin](https://www.linkedin.com/in/alexandra933/), no te preocupes, comenzaremos el taller con un breve repaso de lo que necesitas saber para participar en el ejercicio.

​El evento se realiza online, utilizando como soporte herramientas como Miro.

​​​​​🗓️ Fecha: Jueves, 28 de Noviembre a las 18:30

​🕕 Duración: 90 minutos

### Fecha de inicio

28 de Noviembre a las 18:30

### Fecha de fin

28 de Noviembre a las  20:00

### Localización del evento

Online

### Imagen de portada

https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=2,background=white,quality=75,width=400,height=400/event-covers/83/2333978a-6c5a-49c3-a3e2-4070f8a38172

### Redes sociales

https://lu.ma/collaborative-modeling

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/como-event-modeling-manos-a-la-obra

¡Muchas gracias!

**Comment by aquiestaThai** [comment]
Gracias a ti!!!
