### ISSUE TITLE
TRGCON 25

### ISSUE THREAD

**Issue by dbonillaf** [achamorro-dev/eventoswiki#182]
### Nombre o título del evento

Personas, tecnología y negocio.

### Web del evento

https://www.trgcon.com/

### Descripción corta

La TRG es una conferencia sobre diseño, construcción y comercialización de servicios digitales que nace alrededor de la heterogénea Comunidad de suscriptores de La Bonilista, la newsletter semanal sobre emprendimiento tecnológico escrita por David Bonilla.

Es ante todo, un punto de encuentro para gente que «hace cosas» alrededor del software, la innovación tecnológica e Internet: desarrolladores, diseñadores, inversores, comerciales, gente de marketing o soporte, administradores de sistemas o recruiters. Nadie sobra y todos son bienvenidos.

Se organiza cuidando cada detalle de forma enfermiza —desde las acreditaciones hasta la oferta gastronómica— para intentar transformar la asistencia en una experiencia y aportar el mayor valor posible a asistentes, ponentes y patrocinadores.

### Fecha de inicio

16/10/2024 14:30 

### Fecha de fin

18/11/2024 17:00

### Localización del evento

Madrid, España

### Imagen de portada

https://trgcon.com/files/logotrg24sponsor.png

### Redes sociales

https://x.com/tarugoconf

**Comment by achamorro-dev** [comment]
¡Buenas David!

El evento TRGCON 25 ya lo tenía dado de alta 😊 He cambiado las fechas que creo son del 16 al 18 de octubre de 2025 y la portada que de momento usamos la de 2024.

Te dejo enlace debajo, si necesitas que modifique alguna cosa más me dices. Iremos actualizándolo cuando tengamos más información.

https://www.eventos.wiki/eventos/2025/trgcon

Un saludo.

**Comment by dbonillaf** [comment]
Hola Alberto,

Graciñas por tenerlo ya actualizado, no lo había visto.

Te paso el enlace al vídeo que mejor cuenta cómo es es el evento, por si
quieres cambiar el de SNGULAR por este:
https://vimeo.com/997084048?share=copy#t=0

Un abrazo,
David

**Comment by achamorro-dev** [comment]
¡Actualizado! Muchas gracias David 😊

**Comment by dbonillaf** [comment]
Hola Alberto,

Nos han cambiado las fechas, del 23 al 25 de octubre finalmente.

¡Disculpa las molestias!

**Comment by achamorro-dev** [comment]
@dbonillaf sin problemas! Ya he actualizado las fechas en la web. 😊
