### ISSUE TITLE
Añadir nuevo evento: 

### ISSUE THREAD

**Issue by socratescan** [achamorro-dev/eventoswiki#183]
### Nombre o título del evento

Socracan 2025

### Web del evento

https://www.socracan.org/

### Descripción corta

Get ready for an unforgettable tech event in one of the most unique locations in the Canary Islands. Socracan is not just a conference; it’s an open space for passionate innovators, thinkers, and creators to come together, share knowledge, and challenge the status quo.

### Fecha de inicio

22/05/2025

### Fecha de fin

25/05/2025

### Localización del evento

Hotel NH Imperial Playa, C. Ferreras, 1, 35008 Las Palmas de Gran Canaria, Las Palmas, España

### Imagen de portada

https://drive.google.com/file/d/1bw4tepie4640DuY9X0aMYXjmULL00aYt/view?usp=sharing

### Redes sociales

https://x.com/socracan , https://www.linkedin.com/in/socrates-canaries-286a26276/

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2025/socracan

¡Muchas gracias!
