### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by ddialar** [achamorro-dev/eventoswiki#19]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: JSDay Canarias
- **Descripción corta**: The greatest conference for JavaScript professionals
- **Fecha de inicio**: 25/05/2023
- **Fecha de fin**: 28/05/2023
- **Localización del evento**: Tenerife, Canary Islands
- **Imagen de portada**: https://drive.google.com/file/d/14TeMQ_2Xktm_zFGb0kRGpEN8sKLd0ejb/view?usp=share_link
- **Web del evento**: https://jsdaycanarias.com
- **Redes sociales**: https://twitter.com/canariasjs, https://www.linkedin.com/in/canariasjs
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
✅ Done

https://www.eventos.wiki/eventos/2023/jsday-canarias
