### ISSUE TITLE
T3chFest

### ISSUE THREAD

**Issue by alcastrob** [achamorro-dev/eventoswiki#2]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- T3chFest
- **Descripción corta**: 
- 2/3/2023
- 3/3/2023
- Auditorio Universidad Carlos III de Madrid. Avenida de la Universidad, 30. 28911 Leganés. Madrid
- **Imagen de portada**:
- https://t3chfest.es/2023/
- https://medium.com/t3chfest
- https://es.linkedin.com/company/t3chfest
- https://instagram.com/t3chfest
- https://www.youtube.com/user/t3chFest
- https://t.me/t3chfest
- https://twitter.com/t3chfest
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
✅ Done:

https://www.eventos.wiki/eventos/2023/t3chfest
