### ISSUE TITLE
SalmorejoTech

### ISSUE THREAD

**Issue by MarcosRigal** [achamorro-dev/eventoswiki#20]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: SalmorejoTech
- **Descripción corta**:  Tu evento tecnológico con sabor cordobés
- **Fecha de inicio**: 28/04/23
- **Fecha de fin**: 28/04/23
- **Localización del evento**: Córdoba
- **Imagen de portada**: https://salmorejo.tech/2022/images/seo/salmorejo_fondo.jpg
- **Web del evento**: https://salmorejo.tech/2023/
- **Redes sociales**: Twitter: https://twitter.com/AulaSL
- **Detalles**(esta información aparecerá como contenido del evento): SalmorejoTech es un evento tecnológico para todos aquellos dispuestos a aprender

**Comment by achamorro-dev** [comment]
✅ Done

https://www.eventos.wiki/eventos/2023/salmorejo-tech

**Comment by MarcosRigal** [comment]
Mil gracias <3

**Comment by achamorro-dev** [comment]
¡¡Gracias a ti Marcos!!
