### ISSUE TITLE
Zurracapoteconf

### ISSUE THREAD

**Issue by juannietogarcia** [achamorro-dev/eventoswiki#21]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**:  Zurracapoteconf 2023
- **Descripción corta**:  "Presente, pasado y futuro de las comunidades Tech en La Rioja, conectadas con el mundo"
- **Fecha de inicio**: 3 de Marzo
- **Fecha de fin**: 5 de Marzo
- **Localización del evento**: Logroño
- **Imagen de portada**:
- **Web del evento**: https://zurracapoteconf.appspot.com/
- **Redes sociales**: https://twitter.com/zurracapoteconf, https://www.linkedin.com/company/zurracapoteconf/
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
Hola @juannietogarcia

Muchas gracias por la solicitud de alta del evento. ¿Está confirmado este evento? En la web veo que toda la información es del 2022.

De todas formas lo he dado de alta: https://www.eventos.wiki/eventos/2023/zurracapoteconf

**Comment by juannietogarcia** [comment]
Hola Alberto,

Si esta confirmado y estamos trabajando en actualizar.

**Comment by achamorro-dev** [comment]
Muchas gracias @juannietogarcia
