### ISSUE TITLE
Meetup Machine Learning Spain

### ISSUE THREAD

**Issue by sorayaML** [achamorro-dev/eventoswiki#22]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Meetup Machine Learning Spain**: 
- ¿Cómo estáis? Nosotros ávidos de seguir compartiendo experiencias y aprendiendo sobre Machine Learning e IA de los cracks que tenemos confirmados para este jueves 1 de diciembre. 

​Llevamos bastante tiempo detrás de un referente del Software Libre y de las comunidades tecnológicas para que viniese a hablarnos, desde su perspectiva académica y rigurosa, sobre ​Stable​ Diffusion​. Por fin le tendremos aquí y todo los que sale de él es oro puro, por lo que estamos deseando absorber y aprender de todo lo que nos comparta.

​Y, como sabéis, el Machine Learning para nosotros va unido inexorablemente a las cervezas (con o sin), a esa cultura de compartir en ambiente distendido​ y entre personas con intereses muy similares en cuanto a tecnología. Así que era hora ya de que alguien nos contara cómo contribuye el ML a crear las cervezas más ricas...: 
- **1/12/22**:
- **1/12/22**:
- **Madrid**:
- **![machine_learning](https://user-images.githubusercontent.com/49687866/204482589-5b78bade-d5ea-46c4-9b9f-58dc6e72899c.png)**:
- **[Web del evento](https://www.meetup.com/machinelearningspain/events/290036090)**:
- **Redes sociales**:
- No os lo podéis perder, y es este ​​jueves 1​ de diciembre a las 18.30h en riguroso directo desde el espacio StageONE de SNGULAR, en un modelo híbrido: speakers, organización e invitados presenciales en el estudio (necesitamos confirmación para gestionar la entrada), y demás asistentes en virtual vía youtube (a través del canal [Machine Learning Spain](https://www.youtube.com/channel/UCEveIdakIBDmvUji4MzezUQ)​). Tenemos plazas libres y cerveza​.

Agenda a día de hoy.... (siempre puede haber sorpresas y cambios de última hora, ya sabéis, aquí es impredecible)​.
​
✔️  18.30h Jesús González-Barahona, Associate Professor at URJC, co-founder at Bitergia

​Stable Diffusion para neófitos y neófitas

Abstract:
​Stable Diffusion es un modelo de aprendizaje automático profundo (deep learning) construido para generar imágenes de alta calidad a partir de sus descripciones en lenguaje natural. El modelo fue publicado en agosto bajo una licencia que permite su reutilización y modificación. Desde entonces, han sido muchas sus adaptaciones a distintos ámbitos, desde la producción de videos hasta la de objetos 3D; su combinación con muchos otros programas; y su extensión con nuevas capacidades (como el in-painting o el out-painting).

Toda esta actividad, junto con la generada por otros modelos relativamente similares (como DALL-E o Midjourney) plantea también muchos interrogantes, como por ejemplo, sobre su efecto facilitador de creación de deep fakes, su aprendizaje a partir de obras protegidas por derechos de autor, o su impacto sobre las profesiones relacionadas con la producción gráfica. En la presentación, trataremos de tocar todos estos aspectos, y mantener un debate informado sobre ellos.

✔️  19.30h David Morcuende, New Technologies Expert en Mahou San Miguel

Analítica avanzada en Mahou: cómo aprovechar el machine learning para mejorar la cerveza

Abstract:
​​Exploraremos una vision macro del sector analizando los datos para, posteriormente, ejecutar acciones concretas asistidas por la inteligencia artificial.

✔️ Tras las charlas, nos tomaremos unas cerves para seguir conversando :)

¡Os esperamos! Y si es presencial, mejor que mejor, que hay ganas de verse!

**Comment by achamorro-dev** [comment]
@sorayaML ¿Ya no quieres dar de alta el evento? Lo iba a subir esta tarde.

**Comment by sorayaML** [comment]
> 

Sí, sí :) Perdón, que he cerrado el issue sin saber muy bien... Sorry y ¡mil gracias!

**Comment by achamorro-dev** [comment]
✅ Añadido!

https://www.eventos.wiki/eventos/2022/machine-learning-spain
