### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by francjp** [achamorro-dev/eventoswiki#24]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: Codemotion Madrid 2023
- **Descripción corta**: Codemotion es el evento tecnológico que trae speakers de primer nivel, tanto nacional como internacional. El sitio perfecto para desarrolladores profesionales que quieren conocer sobre las últimas tecnologías y qué está por venir
- **Fecha de inicio**: 09/05/2023
- **Fecha de fin**: 10/05/2023
- **Localización del evento**: Kinépolis. C. Edgar Neville, s/n, 28223 Madrid.
- **Imagen de portada**: ![CDM_2018_logo_payoff_orange_blue_RGB](https://user-images.githubusercontent.com/6509355/215476019-2f5cab3c-2d95-4e1e-ae60-cfa41e558304.jpg)
- **Web del evento**: https://extra.codemotion.com/live-conference-madrid-2023
- **Redes sociales**: https://twitter.com/CodemoMadrid https://www.instagram.com/codemotion_esp/ https://www.linkedin.com/company/codemotion/ https://www.youtube.com/@Codemotionworld/featured
- **Detalles**(esta información aparecerá como contenido del evento): 
## Codemotion Madrid 2023
Codemotion es la plataforma líder que apoya el crecimiento profesional de los desarrolladores y ayuda a las empresas a conectarse con ellos.

### Tres razones por las cuales no puedes perderte nuestra próxima edición
Nuestra conferencia es un imprescindible para los desarrolladores y profesionales de tecnología. Ofrecemos las últimas novedades tecnológicas, y todo lo que se cuece en el desarrollo actual. 

* **Conoce a los desarrolladores**
No hay nada como una conferencia presencial, para sentirse parte de la comunidad y disfrutar de todas sus ventajas: charla con speakers, líderes tech y otros desarrolladores para hacer crecer tu red de contactos.

* **Déjate inspirar por la innovación**
Expande tus horizontes al asistir a charlas de primer nivel, tanto de speakers nacionales como internacionales. Mejora tus habilidades y experimenta de primera mano charlas donde verás casos reales, y empresas mostrando las últimas novedades en tecnología.

* **Siéntete parte de algo único**
Disfruta de las buenas sensaciones, en un sitio donde todos son bienvenidos. Diversidad e inclusión son parte de nuestro ADN, y celebramos esto a través de charlas y actividades más allá del código: crecimiento personal, soft skills, liderazgo y mucho más!

**Comment by achamorro-dev** [comment]
✅ Done!

https://www.eventos.wiki/eventos/2023/codemotion-madrid
