### ISSUE TITLE
Añadir nuevo evento - DevOpsDays Cáceres 2023

### ISSUE THREAD

**Issue by SantiMA10** [achamorro-dev/eventoswiki#27]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: DevOpsDays Cáceres 2023
- **Descripción corta**:  DevOpsDays Cáceres 2023 es un evento sin ánimo de lucro, que intenta rellenar la ausencia de conferencias tecnológicas enfocadas al mundo open source que existe en esta región de España. Al mismo tiempo, por parte de la organización, queremos dar una oportunidad para dar a conocer las nuevas tendencias en un entorno muy poco habitual, ya que la ciudad de Cáceres es un marco incomparable. En el cual se intentará desarrollar una conferencia de un formato diferente al que estamos acostumbrados a asistir, donde los asistentes podrán ser al mismo tiempo protagonistas durante los open spaces.
- **Fecha de inicio**: 28 de abril 2023
- **Fecha de fin**: 29 de abril 2023
- **Localización del evento**: Cáceres
- **Imagen de portada**: https://www.instagram.com/p/Co73kVgrhOx/
- **Web del evento**: https://devopsdays.cc/ and https://devopsdays.org/events/2023-caceres/welcome/
- **Redes sociales**: https://www.instagram.com/devopsdayscc/ https://twitter.com/DevOpsDaysCC https://www.linkedin.com/company/devopsdayscc https://www.facebook.com/DevOpsDaysCC https://www.youtube.com/channel/UCt5kxNPkNGifadwaOgHn_tg
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by SantiMA10** [comment]
Como @curratore es el organizador, cierro esta issue y que se añada con la info que ha puesto él

**Comment by achamorro-dev** [comment]
¡Muchas gracias @SantiMA10 por tu petición! Si quieres echarle un vistazo, este es el resultado:

https://www.eventos.wiki/eventos/2023/devopsdays-cc
