### ISSUE TITLE
DevOpsDaysCC 2023

### ISSUE THREAD

**Issue by curratore** [achamorro-dev/eventoswiki#28]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: 
DevOpsDays Cáceres 2023
- **Descripción corta**:  
- **Fecha de inicio**: 28/04/2023
- **Fecha de fin**: 29/04/2023
- **Localización del evento**: Cáceres
- **Imagen de portada**: 
![image](https://user-images.githubusercontent.com/1506358/221168839-675239f8-8396-4aa7-88bb-03601cc49ffa.png)
- **Web del evento**: 
https://devopsdays.cc
https://devopsdays.org/events/2023-caceres/welcome/
- **Redes sociales**: 
https://twitter.com/devopsdayscc
https://www.instagram.com/devopsdayscc/
https://www.linkedin.com/company/devopsdayscc
https://www.youtube.com/@devopsdayscc
- **Detalles**(esta información aparecerá como contenido del evento):
DevOpsDays Cáceres 2023 es un evento sin ánimo de lucro, que intenta rellenar la ausencia de conferencias tecnológicas enfocadas al mundo open source que existe en esta región de España.
-**Hashstag**: #devopsdayscc23

**Comment by achamorro-dev** [comment]
¡Muchas gracias @curratore! Por aquí tienes el enlace al evento:

https://www.eventos.wiki/eventos/2023/devopsdays-cc
