### ISSUE TITLE
Añadir nuevo evento (OpenSouthCode 2023)

### ISSUE THREAD

**Issue by linuxonrails** [achamorro-dev/eventoswiki#29]
- **Nombre o título del evento**: Opensouthcode 2023
- **Descripción corta**: Opensouthcode es un evento para promocionar y dar a conocer las tecnologías abiertas: software/hardware libre y opensource.
- **Fecha de inicio**: 9 de Junio 2023
- **Fecha de fin**: 10 de Junio 2023
- **Localización del evento**: [La Térmica - Málaga](https://latermicamalaga.com/)
- **Imagen de portada**: https://www.opensouthcode.org/system/sponsors/logos/000/000/065/large/OSC_large.png
- **Web del evento**: https://www.opensouthcode.org/conferences/opensouthcode2023
- **Redes sociales**: [Facebook](https://www.facebook.com/opensouthcode/) · [Twitter](https://twitter.com/opensouthcode) · [Mastodon](https://floss.social/@opensouthcode) · [YouTube](https://www.youtube.com/@opensouthcode)
- **Detalles**(esta información aparecerá como contenido del evento): Opensouthcode es un evento para promocionar y dar a conocer las tecnologías abiertas: software/hardware libre y opensource. Desde 2016, Opensouthcode ha sido punto de encuentro de las comunidades de tecnologías abiertas en el sur de Europa.

¡¡¡Mil gracias!!! :grin:

**Comment by achamorro-dev** [comment]
✅ Añadido!! Muchas gracias!

https://www.eventos.wiki/eventos/2023/open-south-code
