### ISSUE TITLE
Next.js Conf

### ISSUE THREAD

**Issue by rsbmkJ** [achamorro-dev/eventoswiki#3]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: Next.js Conf
- **Descripción corta**: La próxima conferencia de Vercel, donde presentaran todas las nuevas características de la plataforma y el framework NextJs
- **Fecha de inicio**: 25 de octubre
- **Fecha de fin**: 25 octubre
- **Localización del evento**: online
- **Imagen de portada**: 
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/111892469/192316331-3c32d31a-677f-4bb7-9bd0-af5b51c4d13f.png">

- **Web del evento**: https://nextjs.org/conf
- **Redes sociales**: https://twitter.com/vercel
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
✅ Done:

https://www.eventos.wiki/eventos/2022/nextjs-conf
