### ISSUE TITLE
WordCamp Sevilla 2023

### ISSUE THREAD

**Issue by mpc** [achamorro-dev/eventoswiki#30]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: WordCamp Sevilla 2023
- **Descripción corta**: El congreso anual de los interesados en WordPress en Sevilla
- **Fecha de inicio**: 20 octubre 2023
- **Fecha de fin**: 22 octunre 2023
- **Localización del evento**: Facultad de Bellas Artes de la Universidad de Sevilla
- **Imagen de portada**: 
- **Web del evento**: sevilla.wordcamp.org
- **Redes sociales**: @wcsevilla
- **Detalles**(esta información aparecerá como contenido del evento): Celebraremos este evento anual por primera vez en el centro de Sevilla. Este año estará enfocado en charlas de alta calidad sobre WordPress y en disfrutar juntádonos todos los interesados en WordPress que quieran venir.

**Comment by achamorro-dev** [comment]
✅ Añadido! Muchas gracias Mariano!

https://www.eventos.wiki/eventos/2023/wordcamp-sevilla

**Comment by mpc** [comment]
Gracias a ti. Saludos
