### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by jpsg** [achamorro-dev/eventoswiki#31]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**:  Agile Real Life. Summer edition
- **Descripción corta**: 
- **Fecha de inicio**:  03/06/2023 09:30
- **Fecha de fin**: 03/06/2023 15:00
- **Localización del evento**: Paradigma Digital, Vía de las Dos Castillas, 33. Ática 2. Pozuelo de Alarcón, Madrid.
- **Imagen de portada**: ![header](https://user-images.githubusercontent.com/6588295/224123094-75425971-f978-4d8e-be4c-b1e01936cf7c.JPG)
- **Web del evento**: https://eventos.paradigmadigital.com/agile-real-life
- **Redes sociales**:
- **Detalles**(esta información aparecerá como contenido del evento):

**¿Qué es?**
El próximo sábado 3 de junio, Paradigma Digital organiza la segunda edición del evento “Agile Real Life” . Un espacio en el que hablaremos sobre la evolución de Agile y compartiremos experiencias en torno a cómo nos ayuda a dar soluciones reales a los desafíos actuales del desarrollo de producto digital.

El evento tendrá lugar en nuestras oficinas de Pozuelo, poniendo a vuestra disposición una zona de networking donde poder conectar con el resto de asistentes, ponentes, patrocinadores y otros invitados especiales.
 
¡Te esperamos!

**¿Cuándo y dónde?**
**3 de junio**
09:30h - 15:00h

**Paradigma Digital**
Vía de las Dos Castillas, 33. Ática 2.
Pozuelo de Alarcón, Madrid.
![DSCF0774](https://user-images.githubusercontent.com/6588295/224121696-e922bc5d-7a66-4b6c-bad7-2c00a91d287f.jpg)

Situado en el edificio Ática número 2, cerca del centro comercial Zielo. El evento se realizará en las diferentes salas del edificio, ya que constará de diferentes tracks para poder abarcar todas las charlas que tenemos preparadas para ese día. La keynote  y el picoteo se realizará en nuestra cafetería, un espacio que, además, cuenta con una terraza al aire libre perfecta para hacer networking.

https://paradigmadigital.com/

**¿Cómo llegar?**
![paradigma ubicación](https://user-images.githubusercontent.com/6588295/224119123-a76b8a04-af83-4c37-a74a-a19bcb1569ba.jpg)

**Comment by achamorro-dev** [comment]
✅ Añadido! Muchísimas gracias!!

https://www.eventos.wiki/eventos/2023/agile-real-life
