### ISSUE TITLE
GSAS 2023

### ISSUE THREAD

**Issue by IvanSuarez** [achamorro-dev/eventoswiki#32]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**:  Global Software Architecture Summit (GSAS)
- **Descripción corta**: GSAS is a 3-days summit which aims to attract and connect software architecture experts from all over the world as well as all those interested in building working software to improve their skills, share knowledge, and connect.
- **Fecha de inicio**: October 9, 2023
- **Fecha de fin**: October 11, 2023
- **Localización del evento**: Barcelona, Spain
- **Imagen de portada**: https://gsas.io/images/hero_area/HeroGSAS23.jpg
- **Web del evento**: https://gsas.io/
- **Redes sociales**:
https://twitter.com/gsas_io
https://www.youtube.com/channel/UCMaqWNkifS_POLnEyv527eQ
https://www.instagram.com/gsas_io/

**Comment by achamorro-dev** [comment]
✅ Añadido! Muchas gracias!!

https://www.eventos.wiki/eventos/2023/gsas
