### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by sdelquin** [achamorro-dev/eventoswiki#37]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: PyConES23
- **Descripción corta**: Conferencia nacional de Python
- **Fecha de inicio**: 6 de octubre de 2023
- **Fecha de fin**: 8 de octubre de 2023
- **Localización del evento**: [Aulario de Guajara (Universidad de La Laguna) - Tenerife](https://goo.gl/maps/qQEPracNsqZWCpGu7)
- **Imagen de portada**: https://github.com/achamorro-dev/eventoswiki/assets/1591599/1a149911-d5f2-4e54-8956-82bcfc8ebb8d
- **Web del evento**: https://2023.es.pycon.org
- **Redes sociales**:
  - https://fosstodon.org/@pycones
  - https://twitter.com/PyConES
  - https://instagram.com/pycon_es
  - https://t.me/pycones23_noticias
  - https://www.youtube.com/@PythonES
- **Detalles**(esta información aparecerá como contenido del evento): Os damos la bienvenida a la PyConES, la conferencia de Python más importante de España. Un evento que reunirá a cientos de entusiastas del lenguaje de programación Python, con una agenda increíble en la mejor localización posible.

**Comment by achamorro-dev** [comment]
✅ Done: https://www.eventos.wiki/eventos/2023/pycones

¡Muchas gracias Sergio!
