### ISSUE TITLE
Añadir nuevo evento: T3chFest 2023

### ISSUE THREAD

**Issue by mariomnts** [achamorro-dev/eventoswiki#4]
- **Nombre o título del evento**:  T3chFest 2023
- **Descripción corta**:  Festival de nuevas tecnologías en la Universidad Carlos III de Madrid.
- **Fecha de inicio**: Jueves 2 de marzo de 2023
- **Fecha de fin**: Viernes 3 de marzo de 2023
- **Localización del evento**: Madrid
- **Imagen de portada**: https://t3chfest.es/2023/media/social/t3f.pn
- **Web del evento**: https://t3chfest.es/2023/
- **Redes sociales**: https://twitter.com/T3chFest
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by MarcosBL** [comment]
Ping: https://t3chfest.es/2023/media/social/t3f.pn**g**

<img src="https://t3chfest.es/2023/media/social/t3f.png">

**Comment by achamorro-dev** [comment]
✅ Done:

https://www.eventos.wiki/eventos/2023/t3chfest
