### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by adrianalvarezgonzalez** [achamorro-dev/eventoswiki#5]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: Contratar y gestionar diseñadores sin ser diseñador
- **Descripción corta**: Ismael González, head of product design en Cabify, nos acompaña para explicar su experiencia contratando y gestionando diseñadores.
- **Fecha de inicio**: jue. 29 de septiembre de 2022, 18:30 CEST
- **Fecha de fin**: jue. 29 de septiembre de 2022, 20:30 CEST
- **Localización del evento**: Corunet Entreplanta, Rúa Sor Joaquina, 6, 15011 A Coruña 15004 A Coruña
- **Imagen de portada**: https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F355655529%2F291704233486%2F1%2Foriginal.20220916-104356?w=940&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C127%2C2114%2C1057&s=e7b35d9b1e4669bebd23fd089cb07a10
- **Web del evento**: https://www.eventbrite.es/e/entradas-contratar-y-gestionar-disenadores-sin-ser-disenador-420759762777
- **Redes sociales**:
- **Detalles**(esta información aparecerá como contenido del evento): [Ismael González](https://www.linkedin.com/in/igonzaleznicolas/), jefe de diseño de producto en Cabify, nos acompaña para explicar su experiencia contratando y gestionando diseñadores.

Antes de unirse a Cabify hace más de cuatro años, Ismael cofundó Comprea, una de las primeras startups en España que ofrecía un servicio de compra de supermercado a domicilio. Comprea se fusionó después con Lola Market, que a su vez fue comprada por Glovo.

El evento se celebrará en las oficinas de Corunet/Sngular y empezará a las 18.30. Al término, podremos quedarnos allí para tomar algo y seguir charlando.

El precio de la entrada incluye bebida (cerveza, agua) y comida (unos pinchos).

Graciñas!

**Comment by achamorro-dev** [comment]
✅ Done:

https://www.eventos.wiki/eventos/2022/contratar-y-gestionar-dise%C3%B1adores-sin-ser-dise%C3%B1ador
