### ISSUE TITLE
Destello de contenido sin estilo (FOUC) en modo oscuro

### ISSUE THREAD

**Issue by felixicaza** [achamorro-dev/eventoswiki#50]
Hola, al cambiar a otra vista se produce un destello cuándo el modo oscuro está activado.

https://github.com/achamorro-dev/eventoswiki/assets/38303370/f2fe8f15-5030-4c17-b6d2-262a4807b011

Me gustaría poder contribuir con una PR para solucionar ese error 🙂

**Comment by achamorro-dev** [comment]
Hola @felixicaza muchas gracias por la issue! Este fallo y otro relacionado con el refresco de los próximos eventos están ya detectados y los solucionaré dentro de poco en la migración a Astro 3.

Dejo pendiente el issue hasta que esté implementada la mejora 😊

**Comment by felixicaza** [comment]
@achamorro-dev Estuve haciendo pruebas en local y había logrado solucionarlo con un pequeño script, pero creo que con el soporte de View Transitions en Astro v3, será fácil.

**Comment by achamorro-dev** [comment]
¡Muchas gracias Felix! Ya he comenzado la migración a Astro 3.

Tareas pendientes:

- [ ] Arreglar botón añadir a calendario
- [ ] Navegación desde el calendario a un evento

Entorno de pruebas:

https://eventoswiki-git-astro3-update-achamorro-dev.vercel.app/
