### ISSUE TITLE
KCD Spain 2023

### ISSUE THREAD

**Issue by fernandoescolar** [achamorro-dev/eventoswiki#56]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**:  KCD Spain 2023
- **Descripción corta**: Kubernetes Community Days Spain es la oportunidad de llegar a cientos de personas interesadas en todo lo relacionado con la nube, y en especial en Kubernetes.
- **Fecha de inicio**: 12 de Diciembre de 2023
- **Fecha de fin**: 12 de Diciembre de 2023
- **Localización del evento**: Virtual
- **Imagen de portada**: https://kcdspain.com/images/logos/KCD-logo-white.png
- **Web del evento**: https://kcdspain.com/
- **Redes sociales**:
   - https://twitter.com/kcdspain
   - https://www.linkedin.com/company/kcdspain/
   - https://www.youtube.com/channel/UC2666lycS6cx5a8KL_hBhKA 
- **Detalles**(esta información aparecerá como contenido del evento): KCD Spain es una excelente oportunidad de compartir tu conocimiento en las tecnologías que te apasionan, usando para ello el castellano. No es necesario que seas CTO de ninguna gran empresa para poder colaborar, este es un evento de comunidad y para la comunidad, así que cualquier persona puede proponer una charla y se valorará independientemente de su puesto, raza, género o credo. Lo único importante aquí es compartir ese conocimiento tan valioso que tienes.

**Comment by achamorro-dev** [comment]
✅ Evento añadido! Puedes verlo aquí:

https://www.eventos.wiki/eventos/2023/kcd-spain

¡Muchas gracias Fernando!
