### ISSUE TITLE
Imagen por defecto de eventos

### ISSUE THREAD

**Issue by omorest** [achamorro-dev/eventoswiki#59]
**Problema**

Cuando un evento no añade una imagen, se ve la tarjeta en blanco. como se muestra en la siguiente imagen.

![image](https://github.com/achamorro-dev/eventoswiki/assets/32195484/2f6c2ae0-e41b-43b6-bbdd-1d0a098dd5c2)

**Solución**

Poner una imagen por defecto relacionada con eventos en caso de que no se añada ninguna.

**Comment by achamorro-dev** [comment]
¡Muchas gracias por la issue @omorest!

He añadido que al dar error alguna imagen añada una por defecto. Además he eliminado el evento Monkey Conf porque no veo nada de información y su web lleva sin funcionar mucho tiempo.

¡Feliz viernes!
