### ISSUE TITLE
Agile Real Life

### ISSUE THREAD

**Issue by mrcsmarcos** [achamorro-dev/eventoswiki#6]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**:  Agile Real Life
- **Descripción corta**: El próximo sábado 15 de octubre, Paradigma Digital organiza la primera edición del evento “Agile Real Life” . Un espacio en el que hablaremos sobre la evolución de Agile y compartiremos experiencias en torno a cómo nos ayuda a dar soluciones reales a los desafíos actuales del desarrollo de producto digital.
Esperamos a más de 150 profesionales del mundo digital que podrán elegir entre 8 charlas repartidas en 2 tracks, además de una keynote, sorteos y mucho más.
- **Fecha de inicio**: 15/10/2022
- **Fecha de fin**: 15/10/2022
- **Localización del evento**: Vía de las Dos Castillas, 33, Ática 2 28224 Pozuelo de Alarcón - Madrid
- **Imagen de portada**: https://info.paradigmadigital.com/hubfs/Paradigma_Nueva_Marca/imagenes/agileday_header.jpg
- **Web del evento**: https://eventos.paradigmadigital.com/agile-real-life-2022
- **Redes sociales**: https://twitter.com/paradigmate / https://www.instagram.com/paradigma_digital/ / https://www.linkedin.com/company/paradigma-digital
- **Detalles**(esta información aparecerá como contenido del evento):
El próximo sábado 15 de octubre, Paradigma Digital organiza la primera edición del evento “Agile Real Life” . Un espacio en el que hablaremos sobre la evolución de Agile y compartiremos experiencias en torno a cómo nos ayuda a dar soluciones reales a los desafíos actuales del desarrollo de producto digital.
Esperamos a más de 150 profesionales del mundo digital que podrán elegir entre 8 charlas repartidas en 2 tracks, además de una keynote, sorteos y mucho más.
El evento tendrá lugar en nuestras oficinas de Pozuelo, poniendo a vuestra disposición una zona de networking donde poder conectar con el resto de asistentes, ponentes, patrocinadores y otros invitados especiales.
¡Te esperamos!

**Comment by achamorro-dev** [comment]
✅ Done:

https://www.eventos.wiki/eventos/2022/agile-real-life
