### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by jpsg** [achamorro-dev/eventoswiki#65]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: Agile Real Life Summer edition
- **Descripción corta**: Paradigma Digital organiza la tercera edición del evento “Agile Real Life” . Un espacio en el que hablaremos sobre la evolución de Agile y compartiremos experiencias en torno a cómo nos ayuda a dar soluciones reales a los desafíos actuales del desarrollo de producto digital.
- **Fecha de inicio**: 01/06/2024
- **Fecha de fin**: 01/06/2024
- **Localización del evento**: Paradigma Digital - Vía de las Dos Castillas, 33, Ática 2, 28224 Pozuelo de Alarcón, Madrid
- **Imagen de portada**: https://eventos.paradigmadigital.com/hubfs/twitter_card-Feb-09-2023-08-13-44-1694-AM.jpg#keepProtocol
- **Web del evento**: https://eventos.paradigmadigital.com/agile-real-life
- **Redes sociales**: @paradigmate
- **Detalles**(esta información aparecerá como contenido del evento): El próximo sábado 1 de junio, Paradigma Digital organiza la tercera edición del evento “Agile Real Life” . Un espacio en el que hablaremos sobre la evolución de Agile y compartiremos experiencias en torno a cómo nos ayuda a dar soluciones reales a los desafíos actuales del desarrollo de producto digital. El evento tendrá lugar en nuestras oficinas de Pozuelo, poniendo a vuestra disposición una zona de networking donde poder conectar con el resto de asistentes, ponentes, patrocinadores y otros invitados especiales. ¡Te esperamos!
PD: La keynote y el picoteo se realizará en nuestra cafetería, un espacio que, además, cuenta con una terraza al aire libre perfecta para hacer networking.

**Comment by achamorro-dev** [comment]
✅ ¡Evento añadido! Puedes verlo publicado aquí:

https://www.eventos.wiki/eventos/2024/agile-real-life-summer-edition

¡Muchas gracias!
