### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by jjimenez-autentia** [achamorro-dev/eventoswiki#7]
- **Nombre o título del evento**:  KCD Spain 2022
- **Descripción corta**: Kubernetes Community Days Spain
- **Fecha de inicio**: 15 de noviembre de 2022
- **Fecha de fin**: 16 de noviembre de 2022
- **Localización del evento**: se emitirán en directo y se publicarán en YouTube tras el evento.
- **Imagen de portada**:
- **Web del evento**: https://kcd.smapply.io
- **Redes sociales**:
- **Detalles**: Todo lo relacionado con la nube, y en especial en Kubernetes. Con la intención de acercar el conocimiento sobre computación en la nube a todas aquellas personas que, por una razón u otra, no pueden asistir a los eventos en inglés, surge KCD Spain para conseguir que todo ese conocimiento se extienda lo máximo posible. Este evento está respaldado por la CNCF

**Comment by achamorro-dev** [comment]
✅ Done:

https://www.eventos.wiki/eventos/2022/kcd-spain
