### ISSUE TITLE
Añadir Opensouthcode 2024

### ISSUE THREAD

**Issue by opensouthcode** [achamorro-dev/eventoswiki#81]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**:  Opensouthcode 2024
- **Descripción corta**:  Evento para promocionar las tecnologías y cultura abierta.
- **Fecha de inicio**: 21/06/2024
- **Fecha de fin**:22/06/2024
- **Localización del evento**: La Térmica, Málaga
- **Imagen de portada**:  https://www.opensouthcode.org/system/conferences/logos/000/000/007/original/logo_osc.jpg
- **Web del evento**: https://www.opensouthcode.org
- **Redes sociales**:  X: @opensouthcode 
- **Detalles**(esta información aparecerá como contenido del evento): Opensouthcode es un evento para promocionar y dar a conocer las tecnologías abiertas: software/hardware libre y opensource.
Desde 2016, Opensouthcode ha sido punto de encuentro de las comunidades de tecnologías abiertas en el sur de Europa.

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/open-south-code

¡Muchas gracias!
