### ISSUE TITLE
Vic Mirallas en Madrid

### ISSUE THREAD

**Issue by ventiladormusic** [achamorro-dev/eventoswiki#89]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**:  Vic Mirallas en Madrid
- **Descripción corta**: Vic Mirallas presenta su último álbum "Dudas"
- **Fecha de inicio**: 29 de febrero de 2024
- **Fecha de fin**: 29 de febrero de 2024
- **Localización del evento**: Sala Villanos
- **Imagen de portada**: 
![Diseño sin título](https://github.com/achamorro-dev/eventoswiki/assets/160491444/1c8be88d-5c41-44ba-b6e6-8581b5a61679)

- **Web del evento**: https://www.google.com/search?client=firefox-b-d&q=sala+villanos
- **Redes sociales**: https://www.instagram.com/vicmirallasmusic/?hl=es
- **Detalles**(esta información aparecerá como contenido del evento): Vic Mirallas, es un artista con una brillante y extensa carrera profesional. Sus composiciones mezclan varios estilos musicales como el pop, el R&B y el jazz bajo las influencias del drum and bass y el género urbano, entre otros, ya que el joven multiinstrumentista defiende la creatividad y libertad artística por encima de las etiquetas. Es así como Vic, entre la fusión de diversos estilos, una base consolidada como músico y un extenso back ground en los escenarios, nacionales e internacionales, ha conseguido afianzarse como un referente actual.

**Comment by achamorro-dev** [comment]
Lo siento pero los eventos que se recogen en esta web son sólo sobre tecnología y desarrollo de software.

Un saludo.
