### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by theUniC** [achamorro-dev/eventoswiki#90]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: Devops Barcelona 2024
- **Descripción corta**: We've crafted the best possible DEVOPS conference just for you so you can see the future and get ready before anybody else. We'll gather top-notch speakers and an awesome community eager to share a lot of knowledge. All of this will take place in the very center of the gorgeous city of Barcelona in an excellent venue. What are you waiting for? Go get your tickets!
- **Fecha de inicio**: 14/11/2024
- **Fecha de fin**: 15/11/2024
- **Localización del evento**: Auditori AXA, Barcelona
- **Imagen de portada**:
- **Web del evento**: https://devops.barcelona/?utm_source=confs.tech&utm_medium=link&utm_campaign=devops-barcelona-2024&utm_id=devops-barcelona-2024
- **Redes sociales**: https://twitter.com/devopsbarcelona https://www.instagram.com/devops_barcelona/ https://www.linkedin.com/company/devops-barcelona-conference/ https://www.youtube.com/@devopsbarcelona/videos
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/devops-barcelona

¡Muchas gracias!
