### ISSUE TITLE
Añadir nuevo evento

### ISSUE THREAD

**Issue by theUniC** [achamorro-dev/eventoswiki#91]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: Frontend Barcelona 2024
- **Descripción corta**: Dive into the cutting-edge of web development on December 3rd & 4th, 2024. This premier event in Barcelona is your gateway to the latest trends, technologies, and best practices in frontend development
- **Fecha de inicio**: 03/12/2024
- **Fecha de fin**: 04/12/2024
- **Localización del evento**: Auditori Axa, Barcelona
- **Imagen de portada**:
- **Web del evento**: https://frontend.barcelona/?utm_source=eventoswiki&utm_medium=link&utm_campaign=frontend-barcelona-2024&utm_id=frontend-barcelona-2024
- **Redes sociales**: https://twitter.com/frontendbcn https://www.linkedin.com/showcase/frontend-barcelona-conference
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/frontend-barcelona

¡Muchas gracias!
