### ISSUE TITLE
Evento TofuConf

### ISSUE THREAD

**Issue by pablosirera** [achamorro-dev/eventoswiki#93]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: TofuConf
- **Descripción corta**: El evento #gastrotech donde nadie muere de hambre
- **Fecha de inicio**: Sábado 14 Septiembre 10:00h
- **Fecha de fin**: Sábado 14 Septiembre 19:00h
- **Localización del evento**: Talent Garden - Madrid
- **Imagen de portada**: 
![IMG_0553](https://github.com/achamorro-dev/eventoswiki/assets/25353031/ba7244ac-1a0f-4356-84e5-98953595f0dd)

- **Web del evento**: https://tofuconf.com/
- **Redes sociales**: 
- **Detalles**(esta información aparecerá como contenido del evento):

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/eventos/2024/tofu-conf

¡Muchas gracias!
