### ISSUE TITLE
CHARLA: Mejora tu vida con Extreme Programming. O, al menos, inténtalo.

### ISSUE THREAD

**Issue by khru** [achamorro-dev/eventoswiki#96]
**Muchas gracias por tu ayuda**

- **Nombre o título del evento**: Mejora tu vida con Extreme Programming. O, al menos, inténtalo.
- **Descripción corta**: En esta charla, exploraremos la importancia de abordar el Burnout en entornos laborales con alta rotación y cómo eXtreme Programming (XP) puede ser una solución efectiva. XP fomenta la colaboración, comunicación, simplicidad y feedback continuo, reduciendo el aislamiento y la sobrecarga de trabajo.

Aunque se desarrolló originalmente para el software, sus principios son relevantes en diversos entornos laborales. Descubriremos cómo XP puede mejorar la calidad de vida laboral y mitigar los efectos del Burnout.
- **Fecha de inicio**: 26/03/2024
- **Fecha de fin**: 26/03/2024
- **Localización del evento**: [Calle Campus Universitario de Espinardo, 7, 30100 Espinardo, Murcia](https://www.google.com/maps/place//data=!4m2!3m1!1s0xd6381aae08b97bf:0xf21eda6b7d106c59?sa=X&ved=1t:8290&ictx=111)
- **Imagen de portada**: 
![image](https://github.com/achamorro-dev/eventoswiki/assets/6353105/def00372-79ba-46a1-8baa-1e8e94dde6c3)
- **Web del evento**: [https://www.meetup.com/es-ES/murciadev/events/299592285/](https://www.meetup.com/es-ES/murciadev/events/299592285/)
- **Redes sociales**:
    - https://twitter.com/MurciaDev
    - https://www.linkedin.com/company/murciadev/
- **Detalles**(esta información aparecerá como contenido del evento): Speaker: Emmanuel Valverde Ramos [@evrtrabajo](https://x.com/evrtrabajo)

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/murciadev-mejora-tu-vida-con-extreme-programming

¡Muchas gracias!
