### ISSUE TITLE
13th BcnRust Meetup

### ISSUE THREAD

**Issue by piny4man** [achamorro-dev/eventoswiki#97]
**Muchas gracias por tu ayuda**

No te vamos a obligar a rellenar todo esto pero cuanta más información nos facilites mejor:

- **Nombre o título del evento**: 13th BcnRust Meetup
- **Descripción corta**: "Introduction to programming Microcontrollers with Rust" & "Desvelando la estructura de memoria de los tipos de datos en Rust"  
- **Fecha de inicio**: Martes, 26 de Marzo de 2024 a las 6:30 PM
- **Fecha de fin**: Martes, 26 de Marzo de 2024 a las 8:30 PM
- **Localización del evento**: Adevinta Spain, C/ de la Ciutat de Granada 150, Barcelona
- **Imagen de portada**: https://secure.meetupstatic.com/photos/event/d/5/5/2/600_519654610.webp
- **Web del evento**: https://www.meetup.com/bcnrust/events/299223178/
- **Redes sociales**: https://bcnrust.github.io/
- **Detalles**(esta información aparecerá como contenido del evento):

¡Tenemos nuevo evento con dos charlas!

**Introduction to programming Microcontrollers with Rust** by [Andreas Bergmeier](https://fosstodon.org/@abergmeier)

With Rust getting more and more support for embedded Architectures, it becomes a viable option for use with Microcontrollers. This talk will try to give an overview about the Rust support landscape in this area as well as some real world examples using ESP* devices.

**Desvelando la estructura de memoria de los tipos de datos en Rust** por [Germán Küber](https://www.linkedin.com/in/germankuber/)

Esta charla se sumerge en el fascinante proceso de ejecución de un binario y cómo se mapean los segmentos en la memoria, explorando el propósito y funcionamiento de la memoria stack y heap. Profundizaremos en cómo se organizan en la memoria los valores de los distintos tipos de datos de Rust, incluyendo enteros, char, Vector, slice, String, string slice, estructuras, enumeraciones y punteros inteligentes como Box, Rc, Arc, además de objetos Trait y rasgos de funciones como FnOnce, FnMut y Fn.

En esta ocasión, [Adevinta](https://www.adevinta.es/) será nuestro anfitrión.

**IMPORTANTE**: Por políticas de [Adevinta](https://www.adevinta.es/), se os solicitará vuestro DNI para poder acceder a sus oficinas así que no lo olvidéis o no podréis acceder. También nos piden una lista anticipada de DNIs para preparar el acceso por lo que os agradeceríamos que rellenarais [este formulario](https://forms.gle/MEK7dqykJ3YL9CXd7).

**IMPORTANT**: Due to [Adevinta](https://adevinta.es/)’s policies, you will be asked for your ID to access their offices, so don’t forget it or you won’t be able to enter. They also ask us for an advanced list of IDs to prepare access, so we would appreciate it if you could fill out [this form](https://forms.gle/9jcgNVCKqa9JcGsq9).

¡Habrá un pizzas y bebidas al final del evento! ¡No os lo perdáis!

¡Os esperamos!

PD: La presentación será **una en inglés y otra en español** e intentaremos hacer streaming del evento si es posible técnicamente ([subscribíos al canal de YouTube](https://www.youtube.com/@bcnrust) para que os notifique cuando empecemos la transmisión).

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/bcnrust-13th-bcnrust-meetup

¡Muchas gracias!

**Comment by piny4man** [comment]
@achamorro-dev muchas gracias!
