### ISSUE TITLE
Introduction to programming Microcontrollers with Rust - Girona

### ISSUE THREAD

**Issue by ifraixedes** [achamorro-dev/eventoswiki#98]
- **Nombre o título del evento**: Introduction to programming Microcontrollers with Rust
- **Descripción corta**: With Rust getting more and more support for embedded architectures, it becomes a viable option for use with Microcontrollers
(https://fosstodon.org/@abergmeier)
- **Fecha de inicio**: 20/03/2024 18:00
- **Fecha de fin**: 20/03/2024 19:30
- **Localización del evento**:  Fundació Nord C/Pic de Peguera, 11, 17003 Girona
- **Imagen de portada**: Adjunta a este issue
- **Web del evento**:  https://www.meetup.com/rust-girona/events/299172343/
- **Redes sociales**:  https://twitter.com/FundacioNord https://www.youtube.com/@fundacionord6632
- **Detalles**(esta información aparecerá como contenido del evento): In this talk, Andreas Bergmeier will overview the Rust support landscape in this area and some real-world examples using ESP* devices. This time we have the pleasure of having an international speaker, Andreas Bergmeier [@abergmeier](https://fosstodon.org/@abergmeier)
The event will be exclusively in English and we'll broadcast and record it.

![photo1710755545](https://github.com/achamorro-dev/eventoswiki/assets/1731633/2597954e-8d31-4dad-aed1-d0acbbe77afb)

**Comment by achamorro-dev** [comment]
✅ ¡Añadido! Puedes verlo por aquí:

https://www.eventos.wiki/meetups/2024/rust-girona-introduction-to-programming-microcontrollers-with-rust

¡Muchas gracias!
